### ISSUE TITLE
The Forum Posts

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#13]
Look what I finally figured out how to do:

``` xml
msg ("<iframe width=\"100%\" height=\"344\" src=\"http://textadventures.co.uk/forum/quest\" frameborder=\"0\" allowfullscreen></iframe>")
```

![image](https://user-images.githubusercontent.com/30656341/29346820-94f8d9ac-820d-11e7-8974-52e2b56ba22c.png)

![image](https://user-images.githubusercontent.com/30656341/29346833-b002bfb0-820d-11e7-8932-e06d8da28000.png)

**Comment by XanMag** [comment]
Ha.  That's sweet!

**Comment by KVonGit** [comment]
This adds a whole new level.

The game can now be live!

We can set up a few attributes with IF...THEN... statements for 4 - 6 different passcodes.

When Pixie solves a forum post, when can post this on the forum:

SUCCESS!

Good job, Pix! Now you can return to the game and enter:

```CHEAT SET player.posttwo = 69105```


This will, of course, unlock another post... or something...

**Comment by KVonGit** [comment]
Hehehe...

Who's ready to fuck with Pixie???

Here are a few of the commands I've added:

``` xml
<command name="kv_clear">
    <pattern>Clear the screen</pattern>
    <script>
      ClearScreen
    </script>
  </command>
  <command name="px_cheat">
    <pattern type="string"><![CDATA[^cheat (?<text1>move|set|get) (?<text2>.+)$]]></pattern>
    <script><![CDATA[
      switch (LCase(text1)) {
        case ("move") {
          o = GetObject(text2)
          if (o = null) {
            error ("I cannot find a location called " + text2)
          }
          else {
            player.parent = o
          }
        }
        case ("get") {
          o = GetObject(text2)
          if (o = null) {
            error ("I cannot find an object called " + text2)
          }
          else {
            o.parent = player
          }
        }
        case ("set") {
          msg ("Doing " + text2)
          regex = "(?<object>.+)\\.(?<attribute>\\S+)\\s*=\\s*(?<value>.+)"
          if (not IsRegexMatch(regex, text2)) {
            error ("Sorry, wrong format")
          }
          dict = Populate(regex, text2)
          obj = GetObject(StringDictionaryItem(dict, "object"))
          if (obj = null) {
            error ("Sorry, object not recognised")
          }
          att = StringDictionaryItem(dict, "attribute")
          value = Eval(StringDictionaryItem(dict, "value"))
          set (obj, att, value)
          msg ("Done")
        }
      }
      // NOW YOU CAN:
      // CHEAT MOVE My bedroom
      // CHEAT GET lantern
      // CHEAT SET player.health=60
      // CHEAT SET Mary.parent = lounge
      // CHEAT SET bronze sword.inventoryverbs = Split("Lookat;Drop;Destroy", ";")
    ]]></script>
  </command>
  <command name="kv_showme">
    <pattern>showme</pattern>
    <script>
      // DisplayList ((GetAllChildObjects(player.parent)), false)
      foreach (o, (GetAllChildObjects(player.parent))) {
        msg (o + ", parent: " + o.parent)
      }
    </script>
  </command>
  <command name="kv_showme it">
    <pattern>showme #text#</pattern>
    <script>
      o = GetObject(text)
      msg (o)
      foreach (b, AllObjects()) {
        if (b = GetObject(text)) {
          msg (b.name)
          if (not b.name = null) {
            names = GetAttributeNames(b, true)
            DisplayList (names, false)
            foreach (b, names) {
              msg (b)
            }
          }
        }
      }
      // DisplayList ((GetAllChildObjects(player.parent)), false)
    </script>
  </command>
  <command name="kv_msg">
    <pattern>msg ("#text#")</pattern>
    <script>
      msg (text)
      ProcessText (text)
    </script>
  </command>
  <command name="kv_ShowPanes">
    <pattern>request (Show, "Panes")</pattern>
    <script>
      request (Show, "Panes")
    </script>
  </command>
  <command name="kv_HidePanes">
    <pattern>request (Hide, "Panes")</pattern>
    <script>
      request (Hide, "Panes")
    </script>
  </command>
```

---
I've added a device, to USE to bookmark the various POSTS (complete with numbers) which I'll be scattering around.

There are in-game post objects, and Pixie can actually interact with the forum from in the game.

The 'device' will be named, described, and given new features once I've slept a little bit.

Pixie starts off with the device in inventory. (I think I'm gonna make it a 2n1 tablet/laptop type thing...

---
NOTE: Pixie has commands that work as functions now! This is so he can program the game from within the game... We'll cover our asses with some IF... statements! (OR (I'd rather not, but) we could make a special room with those commands specific to it. USE DEVICE could move Pixie to a special room with all the special commands. LOG OFF could move him back to the main map.)

**Comment by KVonGit** [comment]
Bwahahaha!

Pixie is playing his game right now and doesn't even know it!!!

http://textadventures.co.uk/forum/quest/topic/g60vk5rov0k4uc2sek2nvg/javascript-in-a-command


![image](https://user-images.githubusercontent.com/30656341/29387798-71d17cbe-82a7-11e7-8402-51fbac7d94eb.png)


![image](https://user-images.githubusercontent.com/30656341/29387684-c3887356-82a6-11e7-917c-2f469248a8b0.png)

![image](https://user-images.githubusercontent.com/30656341/29387700-d7ac85e8-82a6-11e7-830f-f7b2e37a7f88.png)

![image](https://user-images.githubusercontent.com/30656341/29387755-39b062d2-82a7-11e7-81a4-a85d965d71b8.png)



Bwahahahahahaha!

**Comment by XanMag** [comment]
Brutal!

**Comment by KVonGit** [comment]
UPDATE:

The file-checker (object/script) doesn't work in the  published game.

(Duh!)

The ```cat``` or ```GetFileURL``` commands DO work though... So we can drop hints about files to view when we see fit.

**Comment by KVonGit** [comment]
Bwahahahahaha!!!

---

http://textadventures.co.uk/forum/quest/topic/u_n5otugokquhpmnu0bdzw/how-do-i-get-time-to-work#d57928f9-27c4-4a93-9083-5892fc1d9cd8


![image](https://user-images.githubusercontent.com/30656341/29483299-efde3d8c-8468-11e7-8afd-24a08ddb0c2b.png)


![image](https://user-images.githubusercontent.com/30656341/29483295-e1fac6d6-8468-11e7-9f6d-a541ab299ff7.png)

**Comment by XanMag** [comment]
So, a couple questions.  
1.  If I put a post in the "General Discussion", Pixie can access this post while in game with this new iFrame deal you've set up, right?  
2.  My post plans on being a list of A LOT of beers, numbered and alphabetized, and the Pix must know which one to ask for at the bar (from none other than Gal Gadot herself).  Posting a beer list of my favorite beers won't be frowned upon on the forum, right?
I'm going to pass the post off as a general discussion about favorite beers.  See any problems here?

**Comment by KVonGit** [comment]
>If I put a post in the "General Discussion", Pixie can access this post while in game with this new iFrame deal you've set up, right?

Correct!

I make an object called ```kv_post_NAME```, then move it to kv_device to have it 'pop up' as an alert in the inventory pane. Then, I put a MAKE INVISIBLE script on the post object under LOOK for the first time.

>My post plans on being a list of 30-40 of my favorite beers, numbered and alphabetized, and the Pix must know which number one to ask for at the bar (from none other than Gal Gadot, of course - he is in MY mind after all). Posting a beer list of my favorite beers won't be frowned upon on the forum, right?
I'm going to pass the post off as a general discussion about favorite beers. See any problems here?

Sounds like a solid plan to me!

>I also plan on maybe linking that post to one of the object posts in the game in the hub. Might need help with that?

When you say "linking that post to one of the object posts in the game in the hub", I think I know what you mean and I'm 99% sure we can easily pull it off.

**Comment by KVonGit** [comment]
```xml
<object name="kv_js_post">
          <inherit name="editor_object" />
          <alias>post about JS</alias>
          <inventoryverbs type="stringlist">
            <value>Look at</value>
          </inventoryverbs>
          <fav><![CDATA[<iframe width="100%" height="344" src="http://textadventures.co.uk/forum/quest/topic/g60vk5rov0k4uc2sek2nvg/javascript-in-a-command" frameborder="0" allowfullscreen></iframe>]]></fav>
          <displayverbs type="stringlist">
            <value>Look at</value>
          </displayverbs>
          <visible />
          <listalias><![CDATA[<p style="color:white;background:black;font-family':Droid Sans'">&nbsp;&nbsp;&nbsp;&nbsp;ALERT: New Forum Post</p>]]></listalias>
          <look type="script"><![CDATA[
            if (not ListContains(player.favorites, kv_js_post)) {
              msg ("This post has been automatically added to you Bookmarks. <br>(USE YOUR ANDROID DEVICE TO VIEW YOUR BOOKMARKS.)")
            }
            msg ("<iframe width=\"100%\" height=\"344\" src=\"http://textadventures.co.uk/forum/quest/topic/g60vk5rov0k4uc2sek2nvg/javascript-in-a-command\" frameborder=\"0\" allowfullscreen></iframe>")
            MakeObjectInvisible (kv_js_post)
            list add (player.favorites, kv_js_post)
            JS.scrollToEnd ()
          ]]></look>
        </object>
```

```xml
<object name="post 23346">
      <inherit name="editor_object" />
      <look><![CDATA[<h2 class="forum-topic-title" name="top">Why is Quest Unpopular?</h2> <img src="https://secure.gravatar.com/avatar/fd0d4fb0d4f66001ed8c262e48930d07?d=retro" />    <b>sonic102                        </b> <small>                          <a href="#23240" class="link-to-this" style="opacity: 0"><span class="glyphicon glyphicon-link"></span></a>                            <span class="local-time" data-time="2013-03-09T19:37:31.0000000+00:00">09 Mar 2013 19:37</span><br/>                                                    </small>Have you wondered why Quest is unpopular?<br/><br/>Well, it was the same when Graham released Inform. There were only a few people who used the system (as compared to the at-time best system TADS). But he did something that the 'unpopular' systems of now did not do: Create a superb game Curses to prove Inform can do really good game.<br/><br/>So we need a really good game, perhaps a collaborated game to prove that Quest is best.<br/><br/>What do you think?<br/>            <hr /><b>This topic is now closed.</b> Topics are closed after 60 days of inactivity.<br/>]]></look>
      <alias>post 23346</alias>
      <usedefaultprefix type="boolean">false</usedefaultprefix>
      <takemsg><![CDATA[You can't take it, Pixie!<br/>(Maybe you can {command:bookmark post #23346:BOOKMARK} it though...)<br/>]]></takemsg>
      <scenery type="boolean">false</scenery>
      <alt type="stringlist">
        <value>post #23346</value>
      </alt>
      <fav><![CDATA[<iframe width="100%" height="344" src="http://textadventures.co.uk/forum/quest/topic/3524/why-is-quest-unpopular#23240" frameborder="0" allowfullscreen></iframe>]]></fav>
      <nocopy type="string"></nocopy>
      <take type="script"><![CDATA[
        msg ("You can't take it.<br/><br/>(Maybe you can {command:bookmark post #23346:BOOKMARK} it...)")
        myScript => {
          if (not ListContains(player.favorites, post 23346)) {
            list add (player.favorites, post 23346)
            msg ("Post 23346 has been added to your bookmarks.<br/>")
            MakeObjectInvisible (post 23346)
          }
          else {
            msg ("You already bookmarked that.")
          }
        }
        post 23346.bookmark = myScript
        list add (post 23346.generatedverbslist, "Bookmark")
        post 23346.displayverbs = Split("Look at", ";")
      ]]></take>
    </object>
```

**Comment by KVonGit** [comment]
>Posting a beer list of my favorite beers won't be frowned upon on the forum, right?

~~~Who cares?~~~

~~~Fuck 'em!~~~

I doubt it. If someone ~~~bitches~~~ ~~~cries about it~~~ complains, just edit the post.

OR

I could make a FAKE forum post. (I've already made one. 

Object: post 23346

```HTML
<h2 class="forum-topic-title" name="top">Why is Quest Unpopular?</h2> <img src="https://secure.gravatar.com/avatar/fd0d4fb0d4f66001ed8c262e48930d07?d=retro" />    <b>sonic102                        </b> <small>                          <a href="#23240" class="link-to-this" style="opacity: 0"><span class="glyphicon glyphicon-link"></span></a>                            <span class="local-time" data-time="2013-03-09T19:37:31.0000000+00:00">09 Mar 2013 19:37</span>
                                                    </small>Have you wondered why Quest is unpopular?

Well, it was the same when Graham released Inform. There were only a few people who used the system (as compared to the at-time best system TADS). But he did something that the 'unpopular' systems of now did not do: Create a superb game Curses to prove Inform can do really good game.

So we need a really good game, perhaps a collaborated game to prove that Quest is best.

What do you think?
            <hr /><b>This topic is now closed.</b> Topics are closed after 60 days of inactivity.
```

<h2 class="forum-topic-title" name="top">Why is Quest Unpopular?</h2> <img src="https://secure.gravatar.com/avatar/fd0d4fb0d4f66001ed8c262e48930d07?d=retro" />    <b>sonic102                        </b> <small>                          <a href="#23240" class="link-to-this" style="opacity: 0"><span class="glyphicon glyphicon-link"></span></a>                            <span class="local-time" data-time="2013-03-09T19:37:31.0000000+00:00">09 Mar 2013 19:37</span>
                                                    </small>Have you wondered why Quest is unpopular?

Well, it was the same when Graham released Inform. There were only a few people who used the system (as compared to the at-time best system TADS). But he did something that the 'unpopular' systems of now did not do: Create a superb game Curses to prove Inform can do really good game.

So we need a really good game, perhaps a collaborated game to prove that Quest is best.

What do you think?
            <hr /><b>This topic is now closed.</b> Topics are closed after 60 days of inactivity.

**Comment by KVonGit** [comment]
I've also recorded a 'voicemail' message.

Just like the alerts and the posts, you can just set it up so the voicemail object is moved into kv_device whenever you want Pixie to receive a voicemail.

**Comment by KVonGit** [comment]
> Well, it was the same when Graham released Inform. There were only a few people who used the system (as compared to the at-time best system TADS). But he did something that the 'unpopular' systems of now did not do: Create a superb game Curses to prove Inform can do really good game.


NOTE:

I thought **Curses** sucked.

I played it through, thinking maybe the end was the pay-off...

Nope.

**Comment by KVonGit** [comment]
I'm cooking up ways the GLITCH can fuck with Pixie!

Do you think randomly covering up the text input field with the location bar will piss him off?

Bwahahaha!

![image](https://user-images.githubusercontent.com/30656341/29494965-d2aec2c8-857a-11e7-9fd4-a15e6302d8a3.png)

![image](https://user-images.githubusercontent.com/30656341/29494968-dc75c838-857a-11e7-9706-6db125b23f50.png)

**Comment by XanMag** [comment]
When you say "linking that post to one of the object posts in the game in the hub", I think I know what you mean and I'm 99% sure we can easily pull it off.

I mean so that he has to access the actual forum on the TA website to see the post that Gal has given him.  He'd use this thingy you've devised.  Or I could just simply screenshot the post I make and allow him to view it that way.  Either way would work, just thought we could run with your new implementation.

**Comment by KVonGit** [comment]
Oh. Yeah:

The posts in the game just iframes. They're just running the actual site inside the game.

I haven't tried clicking a link from inside of that though...

**Comment by KVonGit** [comment]
>So maybe i could comment on how appreciative I am for him helping me with all my tasks by "bejeweling" my Cert of App, one such "bejewelment" being a shard. Hell, I'm a perpetual dumbass so gluing one of the most important artifacts in the universe to a lame certificate sounds like something I would do.

Hehehe!

I just deleted this from the group project.

(I've done that twice, so don't feel bad!)

**Comment by XanMag** [comment]
So that went to the group post??  Damn.  Oops.  I thought I was responding to the other post.  It's all wanly weird on my phone.  Sorry!

**Comment by KVonGit** [comment]
It doesn't say anything at all.

(Mine had some details listed when I did it.)

**Comment by XanMag** [comment]
*wanky ...

**Comment by KVonGit** [comment]
## If I knew Alex, I'd add a scene where we discovered **_he_** was the one causing the glitch to occasionally fuck with Pixie...

---
"Just making sure you're not getting to big for your breeches," smiles Alex. "Tell you what, though... Since you've passed my little test, you can ask me **_one_** question."

\>ask Alex about web editor
This invokes uproarious laughter.

"Oh, Pix," says Alex, giving you a friendly pat on the shoulder. "Pix, Pix, Pix..."

He gives you one more pat on the shoulder, drops you a conspiratorial wink, and turns to the glitch.

"Come on, Ralph!" bellows Alex. "Quit sniffing around for dodos! The time has come for us to move on to the next game!"

The glitch quivers in place for a split second, then it implodes in an ear-popping **_PLOMP!!!_**, which is directly followed by a **_ZAMF!!!_**, and Ralph the penguin appears!

"Will there be a dodo in the next game?" Ralph asks Alex. "I like dodos!"

"Just come on!" Alex snaps. "Tell The Pix 'goodnight', Ralph."

Ralph waddles over to you, looks you right in the eye as seriously as can be, and says, "goodnight, Ralph!"


# THE END

**Comment by KVonGit** [comment]
# NO!

Here it is:

Pixie finally has the glitch cornered (somehow), but he just can't catch it!

Then, all of a sudden (and out of nowhere), Alex appears! He's carrying a Proverbial Torch, which he waves at the glitch, backing it into a corner.

"The only thing that will rid you of that glitch is fire," says Alex, passing you the torch.

**Comment by KVonGit** [comment]
# WEEKEND UPDATE:

You can't log into the forum through the game.

You can only view http://, no https://


# Insert curse words here!

---
### Alex Warren ***did*** approve his NPC cameo though. So that's pretty cool.

I had him pass THE LAMP instead of THE TORCH. (Hehehe.)

---
#### And in breaking news:

# Generalissimo Francisco Franco is still dead!

>"I'm Chevy Chase, and you're not!"
    -Richard Belzer
        -SNL, Season 2
