### ISSUE TITLE
sofar

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#19]
```xml
  <walkthrough name="sofar">
    <steps type="simplestringlist">
      look at ALERT: Welcome, Pix!
      look at post about JS
      look
      take brochure
      go to DL's Room
      look at desk
      take globe
      take disk
      west
      give to rh planet disk
      look at Richard Headkid's desk
      switch on PC
      press ANY key
      enter blue phone-booth
      look at alert from KV
      x sticky
      69105
      look at ALERT: Welcome to KV's world!
      o
      n
      ride bird
      e
      feel
      use lamp
      get all
      search pouch
      enter phone
      use token
      open mini
      get shard
      travel
      look at ALERT: KV's world completed!
      ask xm about music
      ask xm about music
      ask xm about anything
      get pill
      give pill to xm
      use interface
      frittata
      enter portal
      get head
      wear it
      use flash on slot
      push button
      play drums
      get flash
      take off head
      drop it
      enter portal
      give flash to xm
    </steps>
  </walkthrough>
```

**Comment by XanMag** [comment]
My daughter had to use the computer tonight for homework so I didn't get around to updating my part of the game.  I will make time for this - hopefully tomorrow.  Sorry!

**Comment by KVonGit** [comment]
No problem, XM!

I've been editing a bunch of shit out anyway...

(The story got out of my control. Sorry about that!)

**Comment by KVonGit** [comment]
# Okay, fellow adventure-makers:

## We've got less than 4 actual minutes of play time (when you know what to do).

>\> dance
XanMag sees your movement and matches it with much more precision and professionalism.
Game time: 0:03:16


**Real-game-time calculator** ***script***:
```C++
x = game.timeelapsed
game.hours = x / 3600
time = x%3600
game.minutes = x/60
x = time%60
game.seconds = x
msg ("<br/>Game time: " + game.hours + ":{if game.minutes<10:0}" + game.minutes + ":{if game.seconds<10:0}" + game.seconds)
```

**Comment by XanMag** [comment]
I am in full realization that you are probably annoyed with my lack of input... sorry!  The sandman and the beerman got a hold of me and prohibited me from keeping my promise!  I will add in a little while.  Trying to today but definitely before the weekend is over.

**Comment by KVonGit** [comment]
> I am in full realization that you are probably annoyed with my lack of input... sorry!  The sandman and the beerman got a hold of me and prohibited me from keeping my promise!  I will add in a little while.  Trying to today but definitely before the weekend is over.

No way! Everyone is cool!

I just played it through on the timer, and I was like, "damn..."

I don't think Pixie can even play it until he gets back home, anyway. So, we've got at least, what... a week?

Plus, that's definitely not the deadline, nor is there one.

---
But... since you haven't gotten to it yet... I am about to commit my changes, so download before you start editing, please, sir. (I had my stuff all messed up!)

---
Plus: I knew everything to do when I played it through. I guess you'd have to multiply that times, oh... let's call it: 10 to get the first time play-through time. (This, of course, is a wild theory.)

(There's also no end-game yet.)

---
The only reason I'd rush is to get it to Pix before he finds out about it.

I have posted about this on the group project Issues about 5 times (and deleted each).

I also accidentally posted two screenshots on the forum while helping someone out. (I've removed them now, and they didn't reveal much... Except for a room called Hub that RH and XanMag and the Quest Forum were in.... (Whoops!))


---
But yeah...

I wasn't rushing or bitching or anything.

[thumbs up goes here]
