### ISSUE TITLE
Things I added for someone else to possibly use

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#2]
\> open laptop
It appears to be stuck closed. (Maybe XanMag can get it open...)

**Comment by XanMag** [comment]
My XanMag already has a laptop!  Haha.  I will be posting SOME of my code soon
 

    On Sunday, August 13, 2017 6:41 PM, K.V. <notifications@github.com> wrote:
 

 > open laptop
It appears to be stuck closed. (Maybe XanMag can get it open...)—

**Comment by KVonGit** [comment]
I'm up in here adding and changing all sorts of shit in my parts...

(I can use DIFF and PATCH to merge our files together, with all revisions intact, though. So fuck it.)

**Comment by XanMag** [comment]
I've added a bunch of stuff to the hub.  I've named everything with an XM after it.  I do have an 'enter|go in' regex command.  That's the one I'm worried about.  Anything you've added that has an enter|go in command?  We can easily add one of ours to the else if of this script though, right?

**Comment by KVonGit** [comment]
>I do have an 'enter|go in' regex command.  That's the one I'm worried about.  Anything you've added that has an enter|go in command?

I have one in each room with a blue phone-booth, but, yes, we can just combine them if they don't get along with each other.

**Comment by XanMag** [comment]
Mine is a command in the 'hub'.  You have a blue phone booth in the hub, too? 

    On Sunday, August 13, 2017 8:02 PM, K.V. <notifications@github.com> wrote:
 

 
I do have an 'enter|go in' regex command. That's the one I'm worried about. Anything you've added that has an enter|go in command?
I have one in each room with a blue phone-booth, but, yes, we can just combine them if they don't get along with each other.—

**Comment by KVonGit** [comment]
>Mine is a command in the 'hub'.  You have a blue phone booth in the hub, too?

Stop copying me, or I'm gonna tell on you!!!

I have a phone-booth in the hub and in KVs room. One transports you to the other upon dialing the correct number.

My enter command is only for entering the phone-booth in said rooms. (It wouldn't let me make an ENTER verb specific to the phone-booths.)

**Comment by XanMag** [comment]
For writers, we are certainly getting a piss poor results out of our translations!  haha! 

Mine is a command in the 'hub'. You have a blue phone booth in the hub, too?
Stop copying me, or I'm gonna tell on you!!!
I MEANT you have a phone booth in your world AND in the hub, not that I have a phone booth in the hub, same as you.  
Wow.  We are a prime example of poor communication, huh?
    On Sunday, August 13, 2017 9:51 PM, K.V. <notifications@github.com> wrote:
 

 
Mine is a command in the 'hub'. You have a blue phone booth in the hub, too?
Stop copying me, or I'm gonna tell on you!!!I have a phone-booth in the hub and in KVs room. One transports you to the other upon dialing the correct number.My enter command is only for entering the phone-booth in said rooms. (It wouldn't let me make an ENTER verb specific to the phone-booths.)—

**Comment by KVonGit** [comment]
I was trying to be funny that time. (You surely would have seen my phone-booth before making a new one. Ha-ha!)

But yeah... Each booth has a different sticky note with a different number to dial.

You just jump from booth to booth.

---
>Wow.  We are a prime example of poor communication, huh?

We'll be okay.

...one day.

**Comment by XanMag** [comment]
XanMag is carrying quite a few things that you may (or may not) want to implement in the hub.
- beer
- laptop (on which can be seen a word document (don't fuck with that please) and a lot of 'browser tabs'
- iPhone
- music (which can be listened to - comments only, no actual audio)

PS.  I deleted a bunch of stuff off the repo because I wasn't realizing my emails were being posted here as well!!?  Shows what I know, right!

**Comment by KVonGit** [comment]
>a word document

Ooh! Ooh! Can we edit it???

> (don't fuck with that please) 

Curses! Foiled again!!!

>I deleted a bunch of stuff off the repo because I wasn't realizing my emails were being posted here as well!!? Shows what I know, right!

What???

You can reply to the emails, and it posts your reply here? (Is that what you're saying? (Our sobriety levels seem to be different today (which causes random communications breakdowns), so I'm just checking!)))

---
PS

**I'm** less sober than ***YOU*** are!!!

**Comment by XanMag** [comment]
You are certainly less sober than I am.  My two wimpy beers wore off hours ago.

But, yes, I did a lot of replying to your emails and they ended up here.  Now we know.

The word document... you will end up inside the word document and able to read it at that point.  Here you will be able to generate feedback which XanMag is crucially needing but too 'afraid' to publicize.  So, you have to sneak in.

**Comment by KVonGit** [comment]
Pixie isn't a contributor for this repo, by the way. And he doesn't follow anyone on GitHub...

So he shouldn't see these posts.

...unless he for some reason decides to peruse the information I have gathered concerning HVAC/R specifications... which is what I called this repository.

**Comment by KVonGit** [comment]
Do you have audio files for this, XanMag?

**Comment by XanMag** [comment]
Yes.

**Comment by KVonGit** [comment]
https://github.com/KVonGit/HVACR-specifications/tree/master/refrigerant%20charts/audio

**Comment by DarkLizerd** [comment]
I need a sound file...
Something bad, horrible... something about like the sound of nails on a chalk board... maybe 20 seconds...
(I don't thing anyone would be able to listen to much more than that...)
I'm going to add a "Wumpus like" creature to hunt.
It will trigger off of the dancing part, but the music did not cause it... It just happened to happen then.
The source is from what happened elsewhere, but the sound is from space being ripped apart.
There will be a hole created in the northwest corner of the room... BUT it will not be ON the walls, just about a foot or two from it.

Also, where and what IS the hub???
A cave, library, lab, "evil lab?"....

**Comment by KVonGit** [comment]
>Also, where and what IS the hub???
A cave, library, lab, "evil lab?"...

It's sort of the non-existent offices of the Quest forum in this dimension, kind of...


Let's think of it as an undisclosed location.   ... a computer lab of the imagination.

(Pixie does basically end up in our imaginations, after all.  ...and he literally has to in XanMag's parts!)

---
You ARE the idea master, aren't you?!?

That's good stuff, sir!

---
XM!!!

We need you here!  (You've heard what happens when I record audio!  And, even though it's bad and horrible, it isn't quite the sound DL needs!)

**Comment by DarkLizerd** [comment]
Reading that... here is what I "saw".
There is an office building, The Quest Tower, and on the 3rd floor is the Advanced Virtulation Research Lab. 
That is where the "hub" is...
(Someone what to correct that lab name for me???)

**Comment by KVonGit** [comment]
Advanced Virtualization Research Lab


I like it!

The Quest Tower's a nice touch, too!
