### ISSUE TITLE
Game Trailer?

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#24]
I like trailers.

Can you guys make one?

Or can one of you guys do the old, 1970's movie-trailer-guy voice? (All deep and serious and awesome...)

---
This is the best 'trailer' I've made:

[![image](https://user-images.githubusercontent.com/30656341/29910633-3a83e946-8df0-11e7-86da-64ffbd86079e.png)](https://drive.google.com/open?id=0BzGPNwPjOx3TMUNGN2FJM3VOdms "This file is posted on Google Drive")

**Comment by XanMag** [comment]
Did you ever see the x3 intro??  :)

**Comment by KVonGit** [comment]
>Did you ever see the x3 intro??

Well, shit no!

I've been writing this game instead of completing X1!

...but I was not aware of an X3 trailer, no, sir.

**Comment by KVonGit** [comment]
I made credits, but it doesn't work in Quest. (In fact, it crashes the game!)

It works fine in Chrome, though...

Download this and open it in your browser:

https://gist.githubusercontent.com/KVonGit/0f73f925b1ce0140d1f78052c1881201/raw/527baa33dabaf668be4ffdf009a985caa2b60a9c/credits.html

**Comment by KVonGit** [comment]
AHA!

Just click this: http://media.textadventures.co.uk/games/cNFLuCu1cUqmUv0I9_KEIQ/index.html

**Comment by XanMag** [comment]
I thought I had I private publication that I had posted the link in a thread.  Guess not.  I will share the intro/trailer when I get home today or tonight.  I thought it was pretty cool.  Needs a little TLC but it is neat. 

    On Thursday, August 31, 2017 8:13 AM, K.V. <notifications@github.com> wrote:
 

 AHA!Just click this: http://media.textadventures.co.uk/games/cNFLuCu1cUqmUv0I9_KEIQ/index.html—

**Comment by XanMag** [comment]
That's a pretty cool trailer.  I just realized you could click it and watch it!  lol 

    On Monday, September 4, 2017 5:39 PM, K.V. <notifications@github.com> wrote:
 

 Closed #24.—

**Comment by KVonGit** [comment]
Oh, hell!

I meant to use a screenshot from YouTube, with a play button...


Whoops!

**Comment by KVonGit** [comment]
(That's a picture of the 'lead vocalist' from the The Trailer Park Rap saying, 'HAVE A NICE DAY', by the way, XM.)
