### ISSUE TITLE
OFF TOPIC

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#3]
I have the beginnings of a game called Rap Game written...

There is a stage, on which is a microphone and the BOOM.

When you drop the BOOM, you only move to a new room at this point, but that isn't all the BOOM is capable of.

---
The way I picture it:

There are two paths you can take:
1. The DJ
2. The MC

Either way, you'll have a counterpart NPC, and you will be rap heroes, using the lyrics and the bass to defeat evildoers.

---
It's a text-adventure musical. (Complete with opening number.)

---
After reading your email, @XanMag, it appears that you may have a similar itch to scratch?

(I'm not proposing 3 projects at once, by the way. Merely wondering if we should plant the seed.)

**Comment by XanMag** [comment]
Consider your seed planted!!
....
Uh... Wait a minute...
Consider the thought of aforementioned game planted in in my mind.  Sounds like fun! 

    On Sunday, August 13, 2017 8:07 PM, K.V. <notifications@github.com> wrote:
 

 I have the beginnings of a game called Rap Game written...There is a stage, on which is a microphone and the BOOM.When you drop the BOOM, you only move to a new room at this point, but that isn't all the BOOM is capable of.The way I picture it:There are two paths you can take:   
   - The DJ
   - The MC
Either way, you'll have a counterpart NPC, and you will be rap heroes, using the lyrics and the bass to defeat evildoers.It's a text-adventure musical. (Complete with opening number.)After reading your email, @XanMag, it appears that you may have a similar itch to scratch?(I'm not proposing 3 projects at once, by the way. Merely wondering if we should plant the seed.)—

**Comment by KVonGit** [comment]
The timer SHALL be used!

**Comment by KVonGit** [comment]
# The first thing I entered made my sides hurt!
\>ask xan about music
XanMag seems startled by your voice and looks at you in surprise.

"You... you're... you're actually a real person?" Xan cocks his head and looks at you a little closer. "Pix? Is that you? It has to be you. You look like a Pixie." You nod affirmatively and wonder if that was meant to be an insult. 

"Never expected to actually talk ot you face to face. You are exactly as I imagined you being." Again... you are unsure if that's a compliment, indifference, or an insult. The smile on XanMag's face though tells you that he meant no harm by his foot-in-mouth approach to conversation.

"Oh," Xan pauses, "Totally forgot what you asked me." With that, he returns to his tasks.
