### ISSUE TITLE
maxScore

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#30]
If you're using the scoring system, please set up an integer attribute called ```maxScore``` on your NPC.

I have a function that will iterate through all objects with said attribute, add them all up, then set that as game.maxScore.

That was the easiest way I could think of to do it.

That way, we can change it up all we want on our individual NPCs, and the start script will add it all up for us.  

(We could also change the maxScore around during play, depending on whatever, if we wished to really mess with Pixie.  I have it set up right now so it just spouts off random max scores when you enter SCORE, but I don't think Pixie would enjoy that after the second or third time it didn't tell him what his goal was.)

**Comment by DarkLizerd** [comment]
This sounds similar... so...
How do we create quests, and how do we use the scoring system...
(and in simple terms please...)

**Comment by KVonGit** [comment]
```C++
AddQuest (DarkLizerd, "insert_quest_name", "This will print out when the player enters Q or QUEST.")
```

```C++
QuestComplete (DarkLizerd, "insert_quest_name")
```

or 

```C++
QuestFailed (DarkLizerd, "insert_quest_name")
```


---
Don't use any apostrophes in the quest name. ```KV's World``` didn't work for me.

**Comment by KVonGit** [comment]
The hints are similar:

```C++
addHint (object_hint_is_for, "This is the hint.")
```

This will add "Hint 1: This is the hint." to a string list on the object (object.hintlist).

The next hint added will read "Hint 2: Blah blah blah...." and so forth.

You could also just add the string list on the object manually.  Just name the list ```hintlist```, and start them off with "Hint #: " if you want them to be uniform, or start them however you want if you don't dig that style.  It's all good to me!

It won't even hurt my feelings if you don't set up any hints.

(They're your scenes.  I'm just a supporting producer when it comes to you guys' parts.)

**Comment by DarkLizerd** [comment]
OK, you answered in simple terms, but I'm still lost as where to put the commands...
I think for me, the quests would be:
Visit DL_Room
and
Get disk

**Comment by KVonGit** [comment]
Sounds right.

I ```AddQuest``` in the start script to visit my world, then ```CompleteQuest``` after entering the room for the first time.

Then, I add the 'Give something to a friend' Quest ontake for your disk.

So on and so forth.

They just call the functions I made.

**Comment by KVonGit** [comment]
Once I add in all my dumb, little, meaningless, comedic responses for the actions that don't effect anything, I'll put my stuff in the main file so everyone can see everything in the object tree.  I was thinking y'all could just show all the libraries, but I just realized how bad that would suck!

**Comment by KVonGit** [comment]
So, in the startscript, add something like:

```C++
AddQuest (DarkLizerd, "visit_DL_Room", "Visit DL's gateway")
```

Then, after entering your room for the first time:

```C++
QuestComplete (DarkLizerd, "visit_DL_Room")
AddQuest (DarkLizerd, "get_the_disk", "Get the special item from DL's room.")
```


Then on the take script (for the first time) on the disk:

```C++
QuestComplete (DarkLizerd, "get_the_disk")
```

**Comment by DarkLizerd** [comment]
OK, I got the "Get the disk" quest to work, but the "Visit DL world" did not work...
So, I'm 1 for 2 on the quests...

**Comment by KVonGit** [comment]
Sorry DL, sometimes GitHub is slow to send the notifications.  (In fact, I just came back and saw this.  I still haven't got the email.  Ha!  Everyone must be busy on GitHub right now!)

I'll set it up for you though.

```C++
AddQuest (DarkLizerd, "Visit Dark Lizerd's room", "Visit Dark Lizerd's world")
```

Will end up being 

```C++
AddQuest (DarkLizerd, "Visit DL Room", "Visit Dark Lizerd's world")
```


(The second one is the key for the dictionary, and it has the same rules as object names: no apostrophes.)

**Comment by KVonGit** [comment]
Completed Quests:
1. Visit Dark Lizerds room
2. Get the Planet Disk

**Comment by KVonGit** [comment]
>the scoring system

Add an attribute to one of your DarkLizerds called **```maxScore```**.  Make it an integer, and set it at the max points that are available during your parts.

So if you have 100 total points available, do:

```C++
DarkLizerd.maxScore = 100
```


Then my function will automatically add up all the **```maxScore```** attributes and add them up to get the TOTAL maxScore.

---
You award points as you normally would though.  

```C++
IncreaseScore(1)
```

or

```C++
game.score = game.score + 1

```

---

This is just a way to always know the maximum score without us having to fool with any sort of record-keeping at all (except for DarkLizerd.maxScore, of course).

**Comment by KVonGit** [comment]
Now it does this when you enter SCORE:

---
\> score

Your score: 55/&infin;

**True Maximum Score: [ 110 ]**
Took DL's card: 1 point
Picked up DL: 1 point
Examined DL's desk: 1 point
Pressed the planet disk's button: 1 point
Asked DL about the 'other' DL: 1 point
Dropped the strange PNG: 1 point
Switched on the PC: 1 point
Changed the game's name to Pixie Kicks Ass: 1 point
Pressed the ANY key: 10 points
Dialed 69105 to travel to KV's gateway: 5 points
Tried to take the glitch: 10 points
Completed KV's gateway: 10 points
Searched the strange pouch: 10 points
Used the brochure: 1 point
Used the Tandy: 1 point

**Comment by KVonGit** [comment]
Cuh-losed.
