### ISSUE TITLE
2-Step Verification Process

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#31]
UPDATED

```C++
msg ("Are you The Pixie?")
get input {
  result = LCase (result)
  if (StartsWith(result, "y")) {
    result = "y"
  }
  else if (StartsWith(result, "n")) {
    result = "n"
  }
  else {
    MoveObject (player, pxCheck)
    error ("That was a yes or no question.")
  }
  switch (result) {
    case ("y") {
      msg ("Are you sure?<br/><br/>What's the first letter of your last name?")
      get input {
        result = LCase (result)
        if (StartsWith(result, "SECRET LETTER")) {
          result = "SECRET LETTER"
        }
        switch (result) {
          case ("SECRET LETTER") {
            game.isPx = true
            request (Show, "Panes")
            ClearScreen
            msg ("Welcome, Pix!")
            MoveObject (player, Quest Forum)
          }
          default {
            ClearScreen
            msg ("That's not what we have on file.  Sorry!<br/>Please try again.<br/>")
            MoveObject (player, pxCheck)
          }
        }
      }
    }
    default {
      request (Show, "Panes")
      game.isPx = false
      ClearScreen
      msg ("Welcome, Adventurer!")
      MoveObject (player, Quest Forum)
    }
  }
}
```

@DarkLizerd 

How about this?

**Comment by KVonGit** [comment]
Updated:

```C++
MoveObject (player, pxCheck)
request (Hide, "Panes")
ClearScreen
msg ("Are you The Pixie?")
get input {
  result = LCase (result)
  if (StartsWith(result, "y")) {
    result = "y"
  }
  else if (StartsWith(result, "n")) {
    result = "n"
  }
  else {
    msg ("That was a yes or no question.")
    isPx
  }
  switch (result) {
    case ("y") {
      msg ("Are you sure?<br/><br/>What's the first letter of your last name?")
      get input {
        result = LCase (result)
        if (StartsWith(result, "j")) {
          result = "j"
        }
        switch (result) {
          case ("j") {
            game.isPx = true
            request (Show, "Panes")
            ClearScreen
            msg ("Welcome, Pix!")
            MoveObject (player, Quest Forum)
          }
          default {
            msg ("That's not what we have on file.  Sorry!<br/>Please try again.<br/>")
            wait {
              ClearScreen
              isPx
            }
          }
        }
      }
    }
    default {
      request (Show, "Panes")
      game.isPx = false
      ClearScreen
      msg ("Welcome, Adventurer!")
      MoveObject (player, Quest Forum)
    }
  }
}
```

**Comment by DarkLizerd** [comment]
I would say it looks good...
Now we can customize this...
Hard for Pixie...
And easy for anyone else...

**Comment by DarkLizerd** [comment]
I had a thought today, and it would make for a much better start...
As it is, the story kinda starts in the middle...
How about this for a rough new start...
The player wakes up after a hard night partying with friends (us).
At the party, we, or one of us, gives him a note for where to show up tomorrow to see what we did.
The party is because we finished the project. (oddly, the project he will soon be playing...)
He, (the player) is so hung over that he forgets who he is, but he knows that a simple check of
his ID will answer the question...
So, he opens his wallet and the note falls out.
He checks his Id and the name is...
GetInput(player.name)
He then reads the note...
Hey, {player.name}, we finally finished that project we talked about!
Come to {Random address} and check it out!
signed {Random programmer}
So, the player takes a shower, wakes up, gets dressed, grabs a taxi and shows up at the address...
(could put the items in a random order with the comment, "hopefully in the correct order..."
IE: "So, the player has breakfast, gets dressed, takes a shower, grabs a taxi, shows up at the address, wakes up... hopefully in the correct order..."
When the player enters, the current game starts.

When we tell Pixie about this, should we tell him that the name "Pixie" will play a special version?

**Comment by KVonGit** [comment]
Well... it would be more like anyone BUT Pixie would play the special version if we did it this way and Pixie's version is the real one...

It's an awesome opening, and I think it's definitely a good idea.  It's definitely, definitely a damned good way to kick it off.  Except for the switching completely from being Pixie part...

Most of XM's stuff (and it's quite a lot) is dialogue between him and Pix. (And you can tell it's pretty much what Xan would say to Pix in person, too.  It's really good stuff.)

The DarkLizerd stuff that's in there now is also freaking spectacular!  And, I'm telling you, and I mean it now, 99% of that opening idea?  I'm sold!

But...

---
See, we've got a LOT written that was designed especially for Pixie.  I think we went over 5,000 lines of code a couple of days ago (that's counting kvLib, which is over 3,000 lines).

If you play all 3 of our parts right now (which is mainly the most direct path through the game, and not triggering all the pointless, comedic responses), it's 117 turns.  I'd say at least 80 of those turns are things only Pixie would figure out and/or enjoy at all.

Now, I'm not at all saying we shouldn't use your opening.  In fact, I really do dig it.  I'm just saying that if we re-design the rest of the game for people besides Pixie, I'd have to cut out 80% of my commands and 'story' (or lack thereof, ha-ha!)  for anyone who isn't well-versed in Quest to even POSSIBLY be able to understand or enjoy anything at all.  

(Like this room we're cooking up right now: https://drive.google.com/open?id=0BzGPNwPjOx3TdWlxRlpiWGJobENOZzVlWU8xY3VIU3ZVcXNz)


---

So, when we ask if they're Pixie and they say 'no' (or if they say 'yes' and can't prove it), I'll just have a script that removes most of what's written now.  That wouldn't sadden me at all, like I say.  I'd write up some stuff to throw in for the non-Pixie run-through in this, and just put my library into a game by itself.  (My story doesn't overlap with either yours or XM's the way it is right now, anyway, besides the part when RH asks to see your disk to initiate my bit.)

I'd rather it be just for Pixie, but published so anyone with the testicular fortitude is welcome to play.

I'm flexible, though.  As long as Pix can play what I've got in some form or fashion, I'm good.

I'm pretty sure I remember XM voting 'fuck it, the player is Pixie' along with me when we discussed dual plot-lines the last time, though...

...and, like I say, his story-line is all about Pixie and him having conversations.

...and mine's all to do with Pixie's Quest scripting expertise...

The best scene I've got is Alex passing Pixie his lamp and moving on to other things, and I'd probably take that out if we're targeting the non-Pixie players.


---
Here's what I propose, and I also propose that we vote on it:

You write that opening, and you can get the input to find out if it's Pix or not.

If it ***is*** Pixie, the game that's written now (with yours and XM's additions) is loaded.

If it ***isn't*** Pixie, the game that's written now (with yours and XM's additions) is loaded after this message displays:

>Dear " + player.alias +",
Remember when you said you could handle all things Quest-related with your hands tied behind your back when we were drinking last night?  Well, here's your chance to prove it!
>
>I've left town for a month or so, and you're in charge of the Quest forum!
>
>(Be sure to keep a close eye on DL, HK, XM, RH, and KV!  Those guys are supposed to be working on our group project while I'm away!  Don't let them bullshit you around, now!  Hands behind your back, remember???)
>
>Cheers,
>The Pix
>
>PS
>I left you a Pixie mask I had the props guy for the group project whip up.  (If anyone realizes you aren't really me, you're game will most likely end abruptly!)
>
>Good luck! 
(And keep those hands behind your back!)


I don't know...

...but I really, really do like your opening...

**Comment by DarkLizerd** [comment]
OK, It's Pixie... That would make everything easer!!!
And I like your change to the note... Mine was just more of a general note.
(actually, re-reading that... it is not what I read at first, but still good.)

**Comment by DarkLizerd** [comment]
I can write the "new start" story in my local version after I upload my other updates.
Then, if everyone agrees, I'll drop-in Pixie's new start.

**Comment by KVonGit** [comment]
>I can write the "new start" story in my local version after I upload my other updates.
Then, if everyone agrees, I'll drop-in Pixie's new start.

Sounds good!

---
The note:

I was just throwing around a general gist that would keep it Pixiefied.

As long as it tells the player he or she has to play the role of The Pixie somehow, it should work out well.  (Our other NPCs will be able to behave just like they're written already that way.)

I just threw in the game ending abruptly bit off of the top of my head.  It will be Pixie no matter what, as far as my NPCs are concerned.

**Comment by KVonGit** [comment]
Is this Quest Tower?

![qdk-background](https://user-images.githubusercontent.com/30656341/30249983-c97db522-960c-11e7-956e-abc6d0068703.jpg)

I found this in an old version of Quest's directory.
