### ISSUE TITLE
THE END GAME

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#36]
Gentlemen (and I mean no offense by that),

We are now in the home stretch.

We have but a few loose ends:

1. Scoring

I award 100 points.  If anyone else would like to award points, feel free to either post a list or edit them in yourself.

Who will use it?

- [x] KV (already finished)

XM
- [x] using it
    - [ ] submitting a list
    - [x] editing myself
- [ ] not using it

DL
- [x] using it
    - [x] submitting a list
    - [ ] editing myself
- [ ] not using it

2. Hints

I have a string list attribute called ```hintlist``` on each object with hints.

If you'd like hints for objects too, follow the same procedure as number 1.

Who will use it?

- [x] KV (already finished)

XM
- [ ] using it
    - [ ] submitting a list
    - [ ] editing myself
- [ ] not using it

DL
- [ ] using it
    - [ ] submitting a list
    - [ ] editing myself
- [x] not using it

3. Quests

DL and I already have Quests set up.

XM
- [ ] using it
    - [ ] submitting a list
    - [ ] editing myself
- [x] not using it

---

### If you don't wish to have any of the above, that's totally groovy, too!

---
# THE ENDING

Are you writing the ending with the foxes and rabbits, @DarkLizerd ?

It seems to come completely out of left-field, but I'm down to include a fox or rabbit passing through one or two of my rooms.

Will it tie into some foxes and rabbits and a Master that you'll have in the group project?  If so, it sounds like a good idea.  If not, I think we'll need to do some re-writing (more than a little) to make it make sense.  Especially considering it's at the end.  I'm all for making the player/reader ask "what???" with no explanation sometimes, but not at the end.

(The strange-looking bird I have in the Meadow is an idea of Pixie's. So, it's random, but it fits.  And the pouch is from my other games.  (I think those are the only two things I've got in there that make no sense story-wise -- they're just inside jokes...))

---
Now, I'm not saying we shouldn't include it, by any means.

I'm just pointing out something you initially pointed out: we'll have to rewrite some stuff.

I would agree that just a few lines here and there would do it, but Pixie is all about the story making sense and coming together.

Every time I post an example story idea in the group project's thread, he's on top of it -- pointing out any minute discrepancy, contradiction, anachronism, or falsity.

So...

---
I've proofread everything 100 times (excluding the stuff XM just submitted).  I've got my Quests, hints, and scoring set up.  I've got all my things in place in Crate Mart, but Pixie can't get in until the attribute says all of our other stuff has already been done.

I've got two ways to finish from Crate Mart set up:

1.  He gets the shard, enters a crate that has a hole in the bottom of it, enters the hole and finds himself in the entrance of a cave.  There is a sword, a shield and some armor there.  Upon getting the sword and shield and donning the armor, he progresses to the first room of the game (which you recently submitted, DL).  Then, when he wakes up the second time, we all burst in, see he still has the shard from the dream, and TO BE CONTINUED.  (I omitted the Wizard of Oz line.)

2.  He gets the shard, goes back to the hub with it, and either:
    a. A dark figure shows up, snatches the shard and disappears.  TO BE CONTINUED.
    b. The shard explodes into 10 pieces, which all mysteriously vanish.  "I sure hope we get all those back in the group project," says someone.  TO BE CONTINUED.

We can fill in the TO BE CONTINUED in part 1 with the foxes and rabbits.  

OR you (DL) can do whatever you want with it after Pixie enters the hub with the shard from Crate Mart.

#### **I'm totally down with adding in some stuff with foxes and rabbits!  I just want to get started if we're going with it,, so I can get finished with this game and get some good sleep.**

...which will last for about two days.  Then, I'll finish porting **They Call Ya' Mister**, take another two day break...  Then, it's back on the group project, full force.

---
Anyway, I'm not really trying to rush art.

We ***are*** in the home stretch though, you guys!

# Whoo-hoo!

**Comment by XanMag** [comment]
For the scoring, do we just use the typical add score script thing?  I thought I remember seeing a specific bit of code we needed to use?

**Comment by KVonGit** [comment]
Yes, sir.  

Then, you can set up ```XanMag.maxScore```, and just put the integer that is your max score.  Or just let me know what that number is, and I'll drop it in there.

**Comment by DarkLizerd** [comment]
The foxes and rabbits was a left field idea... (very far left field!!!)
I think I would go for the "looping dream" idea. 
But, if someone wanted to add a rabbit here, a fox there... then for the main project, they get explained better...
As it stands, they could be red herrings for now just to confuse Pixie, or the player, as to why they are here.
I've been under the weather this past week, so I will just submit a list shortly, and as for hints, I don't think my parts are that hard... as for you guy's parts...

**Comment by DarkLizerd** [comment]
1 point each: 5 points total.
X desk
push button
take DL in DL Room
take "out of order" sign
talk to the other DL

The keypad was going to be an override for random features
in the DL_Room, if the Bast creature was there or not
and if DL was having lunch, or working on the project.
(Add it if you want to.)

**Comment by KVonGit** [comment]
>The keypad was going to be an override for random features

I really wasn't trying to rush to get finished.  I just wanted to start adding in stuff about foxes, and wabbits, and Masters (oh my!), if we were going to (and if they would be in the group project).

---
I though that maybe/probably everyone was just busy with life and/or work, but I imagined that I had burnt you guys out on this project, which I initially announced would be "small".

There's always time for add-ons and improvements.

---
>As it stands, they could be red herrings for now just to confuse Pixie, or the player, as to why they are here.

I was being a big p---y yesterday, DL.  I was thinking more of what the player may think than I was about the art.  

We shall not pander to the masses!  We shall NOT go gently into a rewrite that explains things to those who will not enjoy the game either way!

I'm about to write the ending just like you spun it and see how it plays out.  (It's going to be campy though.  I'll break down that 'wall' and refer to the game from within the game.  (You know, like when Groucho Marx/Bugs Bunny/Ferris Bueller/Van Wilder talk to the camera during the show?))

I won't grow attached to it or anything.

**Comment by KVonGit** [comment]
\> give beer to xan
He does not want it.

\> give pint to xan
As soon as you pull the beer from your inventory, a spot of drool immediately beads at the corner of XanMag's mouth. He eyes you for a bit before saying, "For me?"

You nod affirmatively and he takes the beer and settles in for a relaxing drink. A few minutes pass and the beer is all but gone and he looks up from his beer-coma reallizing you are still loitering in his personal space.

"Oh, hey, Pix." Xan holds the empty glass above his head. "Cheers! Thanks so much!" 

Xan places the empty glass away and returns to his multi-tasking.
"You really are something special, Pixie. Your wonders know no bounds. But," Xan shrugs and reddens a bit, "I'm pretty inept as you damn well know. If there is any chance at all, could you do a couple more things for me?" Xan returns to his distractions.


"Oh, and, if you don't mind," Xan adds, "There is still one more thing I need help with. "Do you mind?"

\> speak to xm
You startle him with your comment, but he gathers himself and says, "What's up? Feel free to ask me about anything. And I literally mean ANYTHING" You nod, but wonder how much help he could actually be to you.

> msg (XanMag.TaskCount)
1

---
What do I do to get into the daydream, XM?

NOTE:  I simply replaced the XanMag object in version 0.0.90 with your revised XanMag object last night.  (I did the same with all of your objects, unless they didn't exist until your revision.  I those instances, I added the objects to the game object.  I also added your new verbs.)

**Comment by XanMag** [comment]
Looks like I didn't tidy up my turncount script.  Obviously, just one of those responses should be there.  I can correct when I get home.  I also spelled realizing incorrectly!  My goodness.  Did I forget to put an exit from the word document room into the daydream room??  Oops!!  Lol

I think it is supposed to be: in (beat lab, nw (WOB), sw (word document), and se (daydream room).  Sorry once more!!

**Comment by KVonGit** [comment]
\>Looks like I didn't tidy up my turncount script.  Obviously, just one of those responses should be there.  I can correct when I get home.

Done.

\> I also spelled realizing incorrectly!

I didn't even see that!  

Fixed.

\> My goodness. 

My darkness.

\>Did I forget to put an exit from the word document room into the daydream room??  Oops!!  Lol

Umm... You know...

There may well be an exit there!

Hold on...

**Comment by KVonGit** [comment]
I fixed 'reallized'.  (You wanted it to be 'reallised', right?)

---
I added the SE exit (bi-directional) from the Word Doc to the Daydream room.

---
The Word Doc shows up in the bar before giving you the beer.  You want it invisible until you've taken the beer, correct?

 (NOTE: I also made the game understand 'beer' as pint.)

---
>Sorry once more!!

You can take your sorry and stick it where the sun don't shine!  

You should see ANY of my stuff after the first draft!  (Even <s>this</s> **these** comments/posts!)

Ha!  Sometimes I can't even make any sense of my writings an hour down the road!

---
NOTE:

I was just kidding.  I made it 'realizing'.

**Comment by KVonGit** [comment]
\>You can take your sorry and stick it where the sun don't shine!

Meaning: 'it's no problem.'

(Just for clarification's sake.)

**Comment by XanMag** [comment]
The word document shows up the n the bar?!?  Wtf?

The word document is a separate room altogether and should never show up in the bar?  I'm confused!!

Thanks again!

**Comment by KVonGit** [comment]
Whoops... I meant that the exit to the Word Document shows up.

---

A World of Beer
You can see a bar, bartender and taps.

You can go southeast or southwest.

---
It's my copy & paste hack-job, I'm sure.  I'm just making sure I'm not messing up the way the puzzles are laid out.  (Lain out?  Nah... laid out's right.)

I was thinking you didn't want the exit to the word document to be accessible until you have been given the beer.

I'm going to play your version to see how it goes.  That would probably be wise on my behalf.

**Comment by XanMag** [comment]
I was thinking you didn't want the exit to the word document to be accessible until you have been given the beer.

- I wasn't really thinking that because it doesn't matter the order it gets finished in, but it might be a good idea.  Executive decision is yours!!

FYI... beer #7!!

Sent from my iPhone

> On Sep 16, 2017, at 4:32 PM, K.V. <notifications@github.com> wrote:
> 
> I was thinking you didn't want the exit to the word document to be accessible until you have been given the beer.


.

**Comment by KVonGit** [comment]
Number 7?  

Only number 7???

---
I was just trying to follow the previous rhyme scheme.  Talk to XM.  Ask something.  Get a task assigned.  Rinse and repeat.

...so I was basically trying to trigger an event that didn't need to be triggered.

It makes total sense the way the it is.  I was simply trying to over-complicate things.

**Comment by KVonGit** [comment]
> The foxes and rabbits was a left field idea... (very far left field!!!)
> I think I would go for the "looping dream" idea.
> But, if someone wanted to add a rabbit here, a fox there... then for the main project, they get explained better...

...after waking up from the loop dream...

Suddenly, and out of nowhere, you see a red fox standing in the corner of your room.  You immediately point it out and ask the guys if they see it, too.

"Oh, don't worry about that just yet," says DL.  "That's just something leaking over from the group project."

# TO BE BEGUN IN:
# SHARDS OF &infin;

---
\>I don't think my parts are that hard... as for you guy's parts...

Yeah... I'll admit my stuff's jacked up, and I just think it's not that bad because I wrote it.

(Don't worry.  The group project won't be designed for the guy who maintains the programming we're using to create the game, so I'll behave.  The Tower of Hanoi will be my biggest pain in the butt in that game.)

\>The keypad was going to be an override for random features
in the DL_Room, if the Bast creature was there or not
and if DL was having lunch, or working on the project.

That sounds pretty damn neat.

You sure you want me to add it in?  I can't emulate your writing style, sir.  (Neither could I emulate Xan's, were I to try.)

Every time I play, I laugh at damn near every line you guys have written.  My stuff is mostly just designed to frustrate Pixie until he's figured out what stupid thing I'm wanting him to do, with smart-aleck comments thrown in for insignificant responses.

I can do it if you want me to, though.  Or I can paste it in if you post examples on here?

Same goes for the ending, by the way, DL.  I wasn't trying to rewrite your stuff.  I was just showing how I could get the story there, then putting a placeholder of how your bit might go.  The more I think about the foxes and rabbits, the more it grows on me.

---
I really wasn't trying to rush us into a wrap-up, by the way.

I mean, I'm ready to get finished, but I don't wish to rush it, either...

I realize the title of this thread and the way I led into may have been easily interpreted as... well... GAME OVER, but I didn't mean "everybody, out of the pool!"

I'm changing it to THE END GAME.  That's more fitting.

**Comment by DarkLizerd** [comment]
Keep the "Game Over"...
Then, after 8 seconds, add a "?" and evil maniacal laughter...
So... the foxes and rabbits grow on you???  hopefully not as bad as athletes foot fungus... (LOL!!!)
Keypad: naw leave it as it is...
Unless you want to add a few dialed numbers and I could throw in the "bad comments" about what may or may not have happened...
With a default response being... "Didn't you read the sign??? The keypad is out of order!!!"
Anyone is welcome to add any commands to it that they want. 
IE: 911 (American help number) "Suddenly, lights start flashing and sirens blare, and several police rush into the room, but see nothing that requires their attention. However, seeing you at the keypad, ask you if you called the emergency assistance number..."
If you answer yes, you are arrested and taken to jail.
Answer no, and you are accused of lying and you go to jail...
(Side game about how you get out of jail...)

**Comment by KVonGit** [comment]
XM's watching Blazing Saddles.

Good choice!

**Comment by KVonGit** [comment]
DL,

Do you care what I did to your disk and your button, as long as you can press the button and it prints your words (and it still behaves identically)?

(I messed it up again somehow.  You had it working, and I can't find that version.  I just made the disk a surface and changed the verb to the button.)

---
@Both

I just made it so the walkthrough doesn't hang up at Quest Towers during the loading screen.

Just enter your initials in the first step of the walkthrough to make it work right.

...eh... I'll just add it to everyone's right now.

---
DL,

Which part is hardest?

(Wait until I commit this revision I'm working up, then answer that one.)

**Comment by KVonGit** [comment]
XM,

You did the score, you have a taskCount.

Hints or no hints?

**Comment by XanMag** [comment]
Hmm.  Maybe?  Is it sucky if I don't?

**Comment by KVonGit** [comment]
> Is it sucky if I don't?

Not for me...

I made one Quest for you that lasts until your TaskCount is 0:

"Help XanMag out with a thing or few"

---
That would technically be a hint.  (I just put it because DL and I have Quests, and I thought it would avoid confusion.  They might think there's nothing to do if there are no active Quests?  I don't know.)
