### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#38]
How shall we do it?

1. Commit the game file to the main group project repo, don't mention it, and wait 'til Pix finds it.

2. One of us asks Pix if he can do a quick run-through to test out a game, and send him this.

3.  Announce it on the forum and just publish it.  (I'd rather Pixie play it first, but we should vote.)

4.  Invite Pixie as a collaborator in this repo, then wait.

5.  Just send Pix a message (written by us all or something?) with the game attached.

---
DL 
- [ ] 1   NO,NO, NO!!!
- [x] 2  Most direct...
- [ ] 3  NO,NO, NO!!!
- [x] 4  Like it, sneaky! :)
- [x] 5  Direct, but not fun.
- [ ] C

XM
- [ ] 1    
- [ ] 2 
- [ ] 3
- [ ] 4  
- [ ] 5  
- [ ] C

KV
- [ ] 1    
- [ ] 2 
- [ ] 3
- [ ] 4  
- [ ] 5  
- [ ] C

**Comment by XanMag** [comment]
Ask on the forum for beta testers and ask for interested parties to contact one of us via Quests messaging system.  Then provide him the link.

**Comment by KVonGit** [comment]
You think he'll jump on being a beta-tester for Pixie's Quest?


That is quite brilliant, XM!

**Comment by KVonGit** [comment]
Okay, XM.

REV ROT 13 works perfectly.  Just commands.  No text scrambler.

Check it out.  See what you think.

<details>

<samp>

\> x note
Aside from the XM doodles, you have scribed what you viewed from the swirling wall of text while under the influence of some killer weed. It reads:

REV ROT 13

obneqebbz. gur sebz pbasvqragyl jnyxrq naq oevrspnfr, uvf pybfrq gvzr, gurve sbe zrzoref gur bs rnpu gunaxrq Tevttf Ze. naq sbeznyvgl, n nf nyjnlf nf Craarl, Ze. gb unaqrq jnf obk svany Gur gnoyr. gur nebhaq unaqrq orvat abj jrer evooba, tbyq n jvgu gvrq naq oyhr oevtug nyjnlf obkrf, Gur punvef. qrcnegzrag gur bs rnpu gb obk tvsg fznyy n bs cerfragngvba gur jvgu raqrq nyjnlf Tevttf qr Gbhe Gur qbja. jvaqvat or gb frrzrq Tevttf Ze. 12:25. ntnva. jngpu uvf ng ybbxrq Ur haornenoyr. zber rira jvsr lbhe jvgu yhapu sbe yngr orvat znqr juvpu erfcbafvovyvgvrf, zber naq ubhef zber qrznaqrq wbo arj Gur frng. Nqiregvfvat bs Punve Qrcnegzrag gur jva gb lrnef svir gnxra bayl unq Vg bccbeghavgl. gur ng whzcrq ur rzcyblzrag, shgher sbe thnenagrr ab naq ergverzrag, zbgure’f cyna, gb jrqqvat n Jvgu tenqhngvba. craqvat Whar va wbo gur uvz bssrerq unq Craarl Ze. pbzcnal. gur ng vagreafuvc Pnqra’f bs gvzr gur qhevat qverpgbe nqiregvfvat naq negf perngvir n sbe ybbxvat or gb unccrarq Craarlcnvq 1994. bs Nhthfg va Trbetvn bs Havirefvgl gur sebz tenqhngvba uvf nsgre fubegyl qbbe Craarlcnvq’f gur bcrarq gung qernz gung jnf Vg vyyhfgengbe. pnegbba n nf qernz uvf chefhrq be sbbgfgrcf, qnq’f va sbyybjrq ur vs erjneqf orggre ernc naq freir orggre jbhyq ur znlor gung gubhtug ur guvf yvxr gvzrf ng ohg qvfnterr, arire jbhyq Pnqra naq jrnygul, irel jrer Tenag’f gur vg, bs ybbxf gur Sebz Pynff. R Zreprqrf 2012 uvf naq Whyvr, naq Qrerx puvyqera, gjva uvf sbe pybgurf yvar gur bs gbc zvav-znafvba, qbyyne unys-zvyyvba ehfgvp ornhgvshyyl n uvz rnea gb rabhtu orra unq pbzcnal gbl yhpengvir guvf jvgu lrnef avar Ebhtuyl Craarl. Ze. tvira unq ur rssbeg naq gvzr gur sbe haqrecnvq pregnvayl jnf ur sbhe, bs snzvyl jbaqreshy n fhccbeg gb rabhtu znqr nqzvggrqyl Pnqra Nygubhtu gung. bs creprag ragver na rira abg jnf vg snpg, Va qbyynef. zvyyvba gjragl uhaqerq bar nccebnpuvat encvqyl abg jnf unaq, bgure gur ba jbegu, Pnqra’f cnegaref. jrnygul rkgerzryl Tevttf Ze. naq PRB, Craarl, J. Wnzrf znxr gb rabhtu orra unq ubjrire, fhpprffrf, guerr Gubfr cebcbfnyf. ohfvarff uvf bs guerr bayl va rssrpgvir orra unq naq lrnef gjragl-svir arneyl sbe Craarlcnvq gb cvgpurf fnyrf cerfragvat orra unq Tevttf Ze. pbeerpg”. “zvyvgnevyl jrer jub Svthevarf Nezl va vairfg gb Gblf Craarlcnvq bs obneq gur pbaivapr gb gelvat abj jnf Tevttf Ze. Nhthfg. bs jrrx svefg gur bayl jnf vg naq lrne guvf cvgpu fnyrf guvegrragu uvf cerfragvat jnf Tevttf Serq Ze. zrrgvat. obneq n va fghpx fgvyy jnf Pnqra naq yhapu, fpurqhyrq uvf hagvy zvahgrf svsgrra naq oernxsnfg, fvapr ubhef svir orra unq Vg 12:15. uhssrq. naq jngpu uvf ng ybbxrq Pnqra zbenyf? urnygul jvgu zna snzvyl uneq-jbexvat qbja-gb-rnegu n vf Pnqra gung pyrne vg Vf cnzcrerq? gbb nf npebff pbzr punenpgre znva gur Qbrf rabhtu? tbbq vagebqhpgvba guvf Vf Abgrf: Crefbany Snpvr Cevzn bs Pu1

\> decipher ("obneqebbz. gur sebz pbasvqragyl jnyxrq naq oevrspnfr, uvf pybfrq gvzr, gurve sbe zrzoref gur bs rnpu gunaxrq Tevttf Ze. naq sbeznyvgl, n nf nyjnlf nf Craarl, Ze. gb unaqrq jnf obk svany Gur gnoyr. gur nebhaq unaqrq orvat abj jrer evooba, tbyq n jvgu gvrq naq oyhr oevtug nyjnlf obkrf, Gur punvef. qrcnegzrag gur bs rnpu gb obk tvsg fznyy n bs cerfragngvba gur jvgu raqrq nyjnlf Tevttf qr Gbhe Gur qbja. jvaqvat or gb frrzrq Tevttf Ze. 12:25. ntnva. jngpu uvf ng ybbxrq Ur haornenoyr. zber rira jvsr lbhe jvgu yhapu sbe yngr orvat znqr juvpu erfcbafvovyvgvrf, zber naq ubhef zber qrznaqrq wbo arj Gur frng. Nqiregvfvat bs Punve Qrcnegzrag gur jva gb lrnef svir gnxra bayl unq Vg bccbeghavgl. gur ng whzcrq ur rzcyblzrag, shgher sbe thnenagrr ab naq ergverzrag, zbgure’f cyna, gb jrqqvat n Jvgu tenqhngvba. craqvat Whar va wbo gur uvz bssrerq unq Craarl Ze. pbzcnal. gur ng vagreafuvc Pnqra’f bs gvzr gur qhevat qverpgbe nqiregvfvat naq negf perngvir n sbe ybbxvat or gb unccrarq Craarlcnvq 1994. bs Nhthfg va Trbetvn bs Havirefvgl gur sebz tenqhngvba uvf nsgre fubegyl qbbe Craarlcnvq’f gur bcrarq gung qernz gung jnf Vg vyyhfgengbe. pnegbba n nf qernz uvf chefhrq be sbbgfgrcf, qnq’f va sbyybjrq ur vs erjneqf orggre ernc naq freir orggre jbhyq ur znlor gung gubhtug ur guvf yvxr gvzrf ng ohg qvfnterr, arire jbhyq Pnqra naq jrnygul, irel jrer Tenag’f gur vg, bs ybbxf gur Sebz Pynff. R Zreprqrf 2012 uvf naq Whyvr, naq Qrerx puvyqera, gjva uvf sbe pybgurf yvar gur bs gbc zvav-znafvba, qbyyne unys-zvyyvba ehfgvp ornhgvshyyl n uvz rnea gb rabhtu orra unq pbzcnal gbl yhpengvir guvf jvgu lrnef avar Ebhtuyl Craarl. Ze. tvira unq ur rssbeg naq gvzr gur sbe haqrecnvq pregnvayl jnf ur sbhe, bs snzvyl jbaqreshy n fhccbeg gb rabhtu znqr nqzvggrqyl Pnqra Nygubhtu gung. bs creprag ragver na rira abg jnf vg snpg, Va qbyynef. zvyyvba gjragl uhaqerq bar nccebnpuvat encvqyl abg jnf unaq, bgure gur ba jbegu, Pnqra’f cnegaref. jrnygul rkgerzryl Tevttf Ze. naq PRB, Craarl, J. Wnzrf znxr gb rabhtu orra unq ubjrire, fhpprffrf, guerr Gubfr cebcbfnyf. ohfvarff uvf bs guerr bayl va rssrpgvir orra unq naq lrnef gjragl-svir arneyl sbe Craarlcnvq gb cvgpurf fnyrf cerfragvat orra unq Tevttf Ze. pbeerpg”. “zvyvgnevyl jrer jub Svthevarf Nezl va vairfg gb Gblf Craarlcnvq bs obneq gur pbaivapr gb gelvat abj jnf Tevttf Ze. Nhthfg. bs jrrx svefg gur bayl jnf vg naq lrne guvf cvgpu fnyrf guvegrragu uvf cerfragvat jnf Tevttf Serq Ze. zrrgvat. obneq n va fghpx fgvyy jnf Pnqra naq yhapu, fpurqhyrq uvf hagvy zvahgrf svsgrra naq oernxsnfg, fvapr ubhef svir orra unq Vg 12:15. uhssrq. naq jngpu uvf ng ybbxrq Pnqra zbenyf? urnygul jvgu zna snzvyl uneq-jbexvat qbja-gb-rnegu n vf Pnqra gung pyrne vg Vf cnzcrerq? gbb nf npebff pbzr punenpgre znva gur Qbrf rabhtu? tbbq vagebqhpgvba guvf Vf Abgrf: Crefbany Snpvr Cevzn bs Pu1", 13)


boardroom. the from confidently walked and briefcase, his closed time, their for members the of each thanked Griggs Mr. and formality, a as always as Penney, Mr. to handed was box final The table. the around handed being now were ribbon, gold a with tied and blue bright always boxes, The chairs. department the of each to box gift small a of presentation the with ended always Griggs de Tour The down. winding be to seemed Griggs Mr. 12:25. again. watch his at looked He unbearable. more even wife your with lunch for late being made which responsibilities, more and hours more demanded job new The seat. Advertising of Chair Department the win to years five taken only had It opportunity. the at jumped he employment, future for guarantee no and retirement, mother’s plan, to wedding a With graduation. pending June in job the him offered had Penney Mr. company. the at internship Caden’s of time the during director advertising and arts creative a for looking be to happened Penneypaid 1994. of August in Georgia of University the from graduation his after shortly door Penneypaid’s the opened that dream that was It illustrator. cartoon a as dream his pursued or footsteps, dad’s in followed he if rewards better reap and serve better would he maybe that thought he this like times at but disagree, never would Caden and wealthy, very were Grant’s the it, of looks the From Class. E Mercedes 2012 his and Julie, and Derek children, twin his for clothes line the of top mini-mansion, dollar half-million rustic beautifully a him earn to enough been had company toy lucrative this with years nine Roughly Penney. Mr. given had he effort and time the for underpaid certainly was he four, of family wonderful a support to enough made admittedly Caden Although that. of percent entire an even not was it fact, In dollars. million twenty hundred one approaching rapidly not was hand, other the on worth, Caden’s partners. wealthy extremely Griggs Mr. and CEO, Penney, W. James make to enough been had however, successes, three Those proposals. business his of three only in effective been had and years twenty-five nearly for Penneypaid to pitches sales presenting been had Griggs Mr. correct”. “militarily were who Figurines Army in invest to Toys Penneypaid of board the convince to trying now was Griggs Mr. August. of week first the only was it and year this pitch sales thirteenth his presenting was Griggs Fred Mr. meeting. board a in stuck still was Caden and lunch, scheduled his until minutes fifteen and breakfast, since hours five been had It 12:15. huffed. and watch his at looked Caden morals? healthy with man family hard-working down-to-earth a is Caden that clear it Is pampered? too as across come character main the Does enough? good introduction this Is Notes: Personal Facie Prima of Ch1

\> reverse boardroom. the from confidently walked and briefcase, his closed time, their for members the of each thanked Griggs Mr. and formality, a as always as Penney, Mr. to handed was box final The table. the around handed being now were ribbon, gold a with tied and blue bright always boxes, The chairs. department the of each to box gift small a of presentation the with ended always Griggs de Tour The down. winding be to seemed Griggs Mr. 12:25. again. watch his at looked He unbearable. more even wife your with lunch for late being made which responsibilities, more and hours more demanded job new The seat. Advertising of Chair Department the win to years five taken only had It opportunity. the at jumped he employment, future for guarantee no and retirement, mother’s plan, to wedding a With graduation. pending June in job the him offered had Penney Mr. company. the at internship Caden’s of time the during director advertising and arts creative a for looking be to happened Penneypaid 1994. of August in Georgia of University the from graduation his after shortly door Penneypaid’s the opened that dream that was It illustrator. cartoon a as dream his pursued or footsteps, dad’s in followed he if rewards better reap and serve better would he maybe that thought he this like times at but disagree, never would Caden and wealthy, very were Grant’s the it, of looks the From Class. E Mercedes 2012 his and Julie, and Derek children, twin his for clothes line the of top mini-mansion, dollar half-million rustic beautifully a him earn to enough been had company toy lucrative this with years nine Roughly Penney. Mr. given had he effort and time the for underpaid certainly was he four, of family wonderful a support to enough made admittedly Caden Although that. of percent entire an even not was it fact, In dollars. million twenty hundred one approaching rapidly not was hand, other the on worth, Caden’s partners. wealthy extremely Griggs Mr. and CEO, Penney, W. James make to enough been had however, successes, three Those proposals. business his of three only in effective been had and years twenty-five nearly for Penneypaid to pitches sales presenting been had Griggs Mr. correct”. “militarily were who Figurines Army in invest to Toys Penneypaid of board the convince to trying now was Griggs Mr. August. of week first the only was it and year this pitch sales thirteenth his presenting was Griggs Fred Mr. meeting. board a in stuck still was Caden and lunch, scheduled his until minutes fifteen and breakfast, since hours five been had It 12:15. huffed. and watch his at looked Caden morals? healthy with man family hard-working down-to-earth a is Caden that clear it Is pampered? too as across come character main the Does enough? good introduction this Is Notes: Personal Facie Prima of Ch1
List: boardroom.; the; from; confidently; walked; and; briefcase,; his; closed; time,; their; for; members; the; of; each; thanked; Griggs; Mr.; and; formality,; a; as; always; as; Penney,; Mr.; to; handed; was; box; final; The; table.; the; around; handed; being; now; were; ribbon,; gold; a; with; tied; and; blue; bright; always; boxes,; The; chairs.; department; the; of; each; to; box; gift; small; a; of; presentation; the; with; ended; always; Griggs; de; Tour; The; down.; winding; be; to; seemed; Griggs; Mr.; 12:25.; again.; watch; his; at; looked; He; unbearable.; more; even; wife; your; with; lunch; for; late; being; made; which; responsibilities,; more; and; hours; more; demanded; job; new; The; seat.; Advertising; of; Chair; Department; the; win; to; years; five; taken; only; had; It; opportunity.; the; at; jumped; he; employment,; future; for; guarantee; no; and; retirement,; mother’s; plan,; to; wedding; a; With; graduation.; pending; June; in; job; the; him; offered; had; Penney; Mr.; company.; the; at; internship; Caden’s; of; time; the; during; director; advertising; and; arts; creative; a; for; looking; be; to; happened; Penneypaid; 1994.; of; August; in; Georgia; of; University; the; from; graduation; his; after; shortly; door; Penneypaid’s; the; opened; that; dream; that; was; It; illustrator.; cartoon; a; as; dream; his; pursued; or; footsteps,; dad’s; in; followed; he; if; rewards; better; reap; and; serve; better; would; he; maybe; that; thought; he; this; like; times; at; but; disagree,; never; would; Caden; and; wealthy,; very; were; Grant’s; the; it,; of; looks; the; From; Class.; E; Mercedes; 2012; his; and; Julie,; and; Derek; children,; twin; his; for; clothes; line; the; of; top; mini-mansion,; dollar; half-million; rustic; beautifully; a; him; earn; to; enough; been; had; company; toy; lucrative; this; with; years; nine; Roughly; Penney.; Mr.; given; had; he; effort; and; time; the; for; underpaid; certainly; was; he; four,; of; family; wonderful; a; support; to; enough; made; admittedly; Caden; Although; that.; of; percent; entire; an; even; not; was; it; fact,; In; dollars.; million; twenty; hundred; one; approaching; rapidly; not; was; hand,; other; the; on; worth,; Caden’s; partners.; wealthy; extremely; Griggs; Mr.; and; CEO,; Penney,; W.; James; make; to; enough; been; had; however,; successes,; three; Those; proposals.; business; his; of; three; only; in; effective; been; had; and; years; twenty-five; nearly; for; Penneypaid; to; pitches; sales; presenting; been; had; Griggs; Mr.; correct”.; “militarily; were; who; Figurines; Army; in; invest; to; Toys; Penneypaid; of; board; the; convince; to; trying; now; was; Griggs; Mr.; August.; of; week; first; the; only; was; it; and; year; this; pitch; sales; thirteenth; his; presenting; was; Griggs; Fred; Mr.; meeting.; board; a; in; stuck; still; was; Caden; and; lunch,; scheduled; his; until; minutes; fifteen; and; breakfast,; since; hours; five; been; had; It; 12:15.; huffed.; and; watch; his; at; looked; Caden; morals?; healthy; with; man; family; hard-working; down-to-earth; a; is; Caden; that; clear; it; Is; pampered?; too; as; across; come; character; main; the; Does; enough?; good; introduction; this; Is; 

Notes:; Personal; Facie; Prima; of; Ch1; 
Ch1 of Prima Facie Personal Notes: Is this introduction good enough? Does the main character come across as too pampered? Is it clear that Caden is a down-to-earth hard-working family man with healthy morals? Caden looked at his watch and huffed. 12:15. It had been five hours since breakfast, and fifteen minutes until his scheduled lunch, and Caden was still stuck in a board meeting. Mr. Fred Griggs was presenting his thirteenth sales pitch this year and it was only the first week of August. Mr. Griggs was now trying to convince the board of Penneypaid Toys to invest in Army Figurines who were “militarily correct”. Mr. Griggs had been presenting sales pitches to Penneypaid for nearly twenty-five years and had been effective in only three of his business proposals. Those three successes, however, had been enough to make James W. Penney, CEO, and Mr. Griggs extremely wealthy partners. Caden’s worth, on the other hand, was not rapidly approaching one hundred twenty million dollars. In fact, it was not even an entire percent of that. Although Caden admittedly made enough to support a wonderful family of four, he was certainly underpaid for the time and effort he had given Mr. Penney. Roughly nine years with this lucrative toy company had been enough to earn him a beautifully rustic half-million dollar mini-mansion, top of the line clothes for his twin children, Derek and Julie, and his 2012 Mercedes E Class. From the looks of it, the Grant’s were very wealthy, and Caden would never disagree, but at times like this he thought that maybe he would better serve and reap better rewards if he followed in dad’s footsteps, or pursued his dream as a cartoon illustrator. It was that dream that opened the Penneypaid’s door shortly after his graduation from the University of Georgia in August of 1994. Penneypaid happened to be looking for a creative arts and advertising director during the time of Caden’s internship at the company. Mr. Penney had offered him the job in June pending graduation. With a wedding to plan, mother’s retirement, and no guarantee for future employment, he jumped at the opportunity. It had only taken five years to win the Department Chair of Advertising seat. The new job demanded more hours and more responsibilities, which made being late for lunch with your wife even more unbearable. He looked at his watch again. 12:25. Mr. Griggs seemed to be winding down. The Tour de Griggs always ended with the presentation of a small gift box to each of the department chairs. The boxes, always bright blue and tied with a gold ribbon, were now being handed around the table. The final box was handed to Mr. Penney, as always as a formality, and Mr. Griggs thanked each of the members for their time, closed his briefcase, and walked confidently from the boardroom.

</samp>

</details>

**Comment by KVonGit** [comment]
Okay...

So we're either:

A. Sending Pix an invite to collaborate here, kicking back, waiting.

B. Post on the forum looking for beta testers.  Contact one of us for info.  We'll put everyone else off until Pix <s>bites the hook</s> takes the bait.

---

If it's B, I think XM is the most fitting to do the posting.  (No offense, XM.  You're a big dog on the forum. ,Mr. Mod.)

**Comment by KVonGit** [comment]
I wish we got notifications when someone edited a comment, damn it!

I almost missed what you did up there, DL!

That's good stuff!

**Comment by DarkLizerd** [comment]
So... what is option "C"???
The problem is that you are choosing one I like 98.5% and one I like 99%...
A. (98.5%)
B. (99%)

**Comment by KVonGit** [comment]
Oh, sorry, DL!

I thought you said you liked 4 up there the best (which is A here).

C from the first one is B down here.  Which is #issuecomment-331768361

---

I thought I picked one from you and one from <s>peckernuts</s> XanMag!

What are your thoughts?

**Comment by DarkLizerd** [comment]
B is not really listed...
C had no text...

As a collaborator, is not quite the same as a play tester...

**Comment by KVonGit** [comment]
Yeah... I had it all jacked up.

I was just trying to be funny with "C", but I meant it like NONE OF THE ABOVE.

B was XanMag's "C".  He opined we should (he should, hehehe) ask for testers in a post, but hold out for Pixie, who would probably respond directly.

I thought you said you liked the idea of inviting him as a collaborator best, so...

I'm doing it over.  Hell, I've confused myself!

---
- [ ] Invite Pixie to collaborate here, then let him find the game himself
- [ ] XM asks for testers for a new game to PM him on the forum, and gives it to Pix when he takes the bait
- [ ] None of the above.  [Please leave a suggestion in a comment.]

**Comment by KVonGit** [comment]
Looks like we're going with XM's idea.

Woot-woot!

**Comment by KVonGit** [comment]
Uh...

I kind of changed the QFQ avatar to this:

![qfq_avatar](https://user-images.githubusercontent.com/30656341/31537474-f039fff2-afc7-11e7-9381-e0454099a7f7.png)
