### ISSUE TITLE
Text Scrambler Doo-hickey Thingy-ma-bob

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#39]
Okay, the scrambler's script is strong like bear, but Quest doesn't like outputting the strange characters to text.

So...

I made it work with REV ROT 13.

One command is:

decipher ("text", 13)

The next is:

reverse text

That's the best I can come up with.

You may want to go with your original idea: an external site.

...or DL's idea about scanning the wall with a device.

https://github.com/KVonGit/HVACR-specifications/issues/37#issuecomment-331770578

**Comment by KVonGit** [comment]
If we go with REV ROT 13, we can drop him an Alert in the Quest PX whenever we please, to let him know that he needs to use ROT 13, then reverse the text.  (Or we could just drop hints.)

**Comment by KVonGit** [comment]
Or, duh....

We can use the forum to let him know how to decipher it!

**Comment by KVonGit** [comment]
@XanMag 

Wake up!

...or just reply on your lunch break or after work...  That would suffice.

---
What the hell do I do with the decoded message?

How does the game know it got decoded?

Do I 'write it down' on the notepad?

Do I need Lassie to help me?

Is Timmy in the well???

And what of Bambi's mom?  And Princess Leia's homeworld?  (You can't go home again...)

I mean I know why hot dogs and buns are sold in different quantities, but seriously...

How DO they get those ships into those bottles?

Where DOES he get those wonderful toys?

Where the white women at?

...or, more importantly, what do I do with this decoded message?

**Comment by KVonGit** [comment]
I do believe The Idea Master may have stroked some genius.  (Huh-huh-huh...)

If the player must input the seven digit code into the text scrambler, then SCAN the message...

That would require the same amount of thinking, just less copying and pasting.

AND we could script it where Quest knew that the message was 'decoded correctly' for sure.

---
I tried to make a function that matched the original, not coded text to the unscrambled text, and I thought the spacing must be different or something.  Quest said it didn't match.

So I regexed that shit, removed the spaces... Still no dice.

\<insert shrug here>

**Comment by DarkLizerd** [comment]
Another thought...
Make a split variable with the 26 letter, 10 number.
and encode the message using that. then mod that result against 36 to get the encoded value.
That would limit the text to just the standard 36 values.
".,!@#$%^&*()-+="and so on will be ignored.
Then when decoding, add 36 before the decode function to get number within the "legal" range.
No more odd special symbols to worry about.
I assume you want the encoded messages in the code so that someone can't just hack the code to see what the decoded message looks like.
Or... add about 10 to 20 decoded messages in the code, but only 1 message is the real decoded message. Then when the player comes across the encoded message, the enter the keycode and it will retrieve one of the messages, but, if the wrong keycode is used, a different message is displayed. But, just to throw the player off, mod the keycode to the number of messages-1. that way a keycode will always return the same message and therefore look like it decoded the message correctly.
But only the correct key will return the right message.
This will get around having to really decode a message.

**Comment by KVonGit** [comment]
Whoa!

 The reverse rot 13 thing works without a hitch, but damn!

You just laid down some serious shit!

We'll have to use that in the group project, unless you're just pumped and want to use it here.

**Comment by KVonGit** [comment]
```C#
msg ("\"That bloody twit?\" XM says in his best, yet still terrible, English accent gesturing to where he last saw RH.  \"He's some sort of savant I think.  Quite brilliant but a little...\" XM pauses to think.  \"A little off maybe? Better keep an eye on that one, Pix.\"  With a hardy slap on the shoulder, XM spins and returns to next-to-nothing.")
```

Ha ha ha!


Hey!!!

I resemble that remark!

I'm not a twit, I'm a TWAT!  (And that rhymes with CAT, which makes it more demeaning. (I learned that from NecroDeath.))

**Comment by KVonGit** [comment]
I still can't get over "you look like a pixie" either!

That is HIL-A-RI-OUS!!!

---
You know what, XM?

It's on like Donkey Kong!

I had a bit where there was a random chance I'd add my 2¢ when Pix asked about your <s>iBrick</s> iPhone:

<samp>
"Pssht!  An Android's a REAL phone!" chimes in RH from across the hub.
</samp>

---
NOTE:  I really did have this in there at point.  I'm not really putting it back, though.  That was one of things I had in there that interrupted one of you guys' parts, and that was NOT very Fonzie-like of me at all.

---
Then, there's the fact that I like Stephen King, and you like Dean Koontz...

Luckily, neither of the textual representations of my digital selves would be in your imaginarium (unless Gal invited me in...), so chaos doesn't ensue there.

---
I may have asked you this before, XM:

Wars or Trek?

Which Star?

**Comment by XanMag** [comment]
Wars.

Feel free to put in any little jabs at me that you want!  I would enjoy it and not take offense.  I look forward to the good natured ribbing.

Also, I added comments in about everyone after I thought I saw something on github about someone being shady or having a shady double.  If that wasn't true, it made some of my convo a little more fun.

We close to being done, right?

**Comment by KVonGit** [comment]
>Wars.

You have chosen <details>wisely!</details>

>We close to being done, right?

Yup, yup!

...DL may be working on a Wumpus addition for his room, but, besides that, yup.

**Comment by KVonGit** [comment]
I'm shelving the text scrambler.

Don't tell Doctor Agon unless he brings it up...

It works!

Quest just doesn't like the characters it puts out.  It's not the scrambler's fault, you know.

---
<samp>

\>put scrambler on shelf
As you lift the text scrambler to shelve it, you could swear you hear something...  A mumble...

<i>"Fix me, DL!"</i> You can barely hear it.  As if someone were speaking into a pillow.  <i>"Fix me for the group project, DL!  I'm BASIC!  You love me, don't you?!?"</i>

You wipe the corner of one eye (it was just an eyelash or something, not a tear), and you decide to keep the scrambler in your inventory for while longer and just make it invisible.

</samp>

---

# R.I.P.  Text Scrambler

**Comment by DarkLizerd** [comment]
Check out my version...
Encoder 1.2...

**Comment by KVonGit** [comment]
![image](https://user-images.githubusercontent.com/30656341/30902472-0772e772-a331-11e7-9ef6-f6b401341672.png)

**Comment by KVonGit** [comment]
You need to turn this into an app when you finish and sell it for 99&cent;!

**Comment by KVonGit** [comment]
I ***think*** Visual Studio 2015 works with Visual Basic.

In fact, I'm pretty damn sure it does.

**Comment by DarkLizerd** [comment]
Did the decode work as well???
Just copy the Message back into the Source box and Decode...

**Comment by KVonGit** [comment]
>Did the decode work as well???
Just copy the Message back into the Source box and Decode...
That would be the true test...

Oh, yessir!

It worked.  (Sorry.  Just saw that post.)
