### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#4]
What's the title?

My only idea is:
# TRIBUTE

---
>"This is not the greatest ~~~song~~~ game in the world.
"This is just a tribute!"
- Tenacious D

**Comment by XanMag** [comment]
TRIBUTE
subtitled:  "You're the best around."
- Joe Esposito
Haha.  Just kidding.  Tribute is good.
How long will your section take?  Ballpark... 

    On Sunday, August 13, 2017 9:25 PM, K.V. <notifications@github.com> wrote:
 

 What's the title?My only idea is:
TRIBUTE

"This is not the greatest  game in the world.
"This is just a tribute!"
   
   - Tenacious D

**Comment by KVonGit** [comment]
>How long will your section take?  Ballpark...

If I don't decide what I've done so far is all stupid... I'll probably be done tonight. (Unless I see something you've included that I'd like to reference or build off of...)

DL said he has some fixes for his section, too.

---
I'm thinking of making Pixie do some fucked up shit with crates at the end. As a big inside joke...

https://github.com/KVonGit/Quest-Group_Project/wiki/CrateLib-(in-progress)#cratelib

**Comment by XanMag** [comment]
How long will your section take? Ballpark...

I meant... how long is the playtime for your section?  =) 

   

 On Sunday, August 13, 2017 9:37 PM, K.V. <notifications@github.com> wrote:
 

 
How long will your section take? Ballpark...
If I don't decide what I've done so far is all stupid... I'll probably be done tonight. (Unless I see something you've included that I'd like to reference or build off of...)DL said he has some fixes for his section, too.I'm thinking of making Pixie do some fucked up shit with crates at the end. As a big inside joke...https://github.com/KVonGit/Quest-Group_Project/wiki/CrateLib-(in-progress)#cratelib—

**Comment by KVonGit** [comment]
>I meant... how long is the playtime for your section?  =)

Oh!

(Shit... I knew *that*!)

Maybe 5 or 10 minutes, maybe?

---
Is my part stupid? Be honest.

I tried to fantasy it up a little, but ... I don't know...

(I'm going back in and adding funny responses and more details and all that if I stick with what's there, by the way.)

---
ALSO: You'll be able to enter HINT to get hints on my stuff. That will technically shorten the play-time a little.

---
I think it took me 5 minutes to get through DL's the first time, and I may still have missed a few things he had written in.

**Comment by XanMag** [comment]
Oh!(Shit... I knew that!)Maybe 5 or 10 minutes, maybe?
Uh oh.  Mine is likely considerably longer.  Like 45-60 minutes!  Overdoing it AGAIN!! 

    On Sunday, August 13, 2017 9:49 PM, K.V. <notifications@github.com> wrote:
 

 
I meant... how long is the playtime for your section? =)
Oh!(Shit... I knew that!)Maybe 5 or 10 minutes, maybe?Is my part stupid? Be honest.I tried to fantasy it up a little, but ... I don't know...(I'm going back in and adding funny responses and more details and all that if I stick with what's there, by the way.)ALSO: You'll be able to enter HINT to get hints on my stuff. That will technically shorten the play-time a little.I think it took me 5 minutes to get through DL's the first time, and I may still have missed a few things he had written in.—

**Comment by KVonGit** [comment]
>Uh oh.  Mine is likely considerably longer.  Like 45-60 minutes!  Overdoing it AGAIN!!

No problem!

I was holding back. I thought you guys wanted to keep this one small.

Mine will be 30 - 45 if I put in all the things I thought up last night/this morning.

---
Estimating play-time:

I suck at it.

**Comment by DarkLizerd** [comment]
New title and it's position relative to the main project...
**Shards of reality, The prequel, The Disk of Infinite Improbability**
(I assume we have not settled on the main theme for the main project...)
I hope it's not too late for everyone to refocus their parts here...
Story:
We are all working of our parts, XM is busy at his desk looking for something, and a bit "irritated" when interrupted. Pixie (or the player) goes to my world and get the planet disk, which Richard "steals" and disappears... You chase him down to get it back...
The next person grabs it from Pixie and that chase goes on...
Until, finally, Pixie manages to make it back to the hub where XM want's to look at it.
He takes it, looks it over, someone calls it a Planet Disk of Dark Lizerd's home world.
XM replies "Oh, really?" then pushes the button and a grey moon with horizontal and vertical lines appears, slowly rotating...
XM comments, "Ah, I thought so..."
As the moon rotates, a big crater, 1/3 the size of the moon comes into view.
"That's no moon..." someone whispers...
XM replies with a sly smile, "Nope...", pushes a button on an arm band and a black rectangle appears around him, which, like elevator doors close in front of him, then like a second set of doors close over the black rectangle leaving no trace of anyone or thing there...
From behind the group, XM comes out a previously unnoticed door, marked Men's, still drying his hands asking the group, "So, what did I miss?"
(after the discussion of what just happened.)
 XM, the good XM, says, "This is not good, but I think I know how we can stop him, Dark Lizerd, can you open a portal to my lab?"
I do, then in the lab, we work out what it takes to stop the Evil XM...
(game ends)
(The main program could be played without needing to play the intro...)
(Main project starts)
We are in Good XM's lab where he, and his clone workers work out how to stop Evil XM.
Then the main project, we chase XM, or rather the Evil XM, across the several worlds trying to catch and stop him... 
We need the Shards of Reality to stop his teleport band. We need to collect 10(?) to power the device, but, as we track them down, he is sometimes just one step ahead of us (the player) and he gets some...
It could be a random chance that he gets them first, or pre-selected.

Like it???
If we want to continue this to a next project... ZM escapes somehow...
Or, the device sends him into a "phantom zone" forever... 
(At least until he escapes and we need the player to catch him again...

KVonGit... If we go with this idea, shorten you part to about 10 minutes, and move your idea to the main project...

**Comment by KVonGit** [comment]
@DarkLizerd 

Shorten my part? (laughing maniacallly)

I'm not laughing at you, DL, I promise...

Have you played through XM's ***first*** part?


**PLUS:** I just made it fucking insane.

Uploading what I've got now....

Pixie can use ALL JS.set commands!

He can use MoveObject, CloneObject, msg, GetFileURL, he can actually interact with the forum....


There's even a part where he finds The God Device, and you can EXPERIENCE The God Device (which just lets you play in an iframe...)

I've figured out how to read text files from the local directory, too!


Uploading now... (Did I say that already?)

---
PS 

I may need to make this a separate game if you guys don't want to watch out for all the cheats he'll be able to use!

He won't have all of his Pixie powers in the beginning... but it won't take long to build them up...

Right now all the powers are available.


Go check it out!

Somebody stop me!!!

**Comment by KVonGit** [comment]
https://github.com/KVonGit/HVACR-specifications/raw/master/refrigerant%20charts/4px_prototype002.quest

**Comment by KVonGit** [comment]
>Shards of reality, The prequel, The Disk of Infinite Improbability

This sounds pretty cool...

I have no plot, per se. I'm just working on the mechanics.

---
I plan for my NPC (RH not KV) to talk shit about XanMag's iPhone at random when he's asked about it. (Android's a REAL device! And Pixie's NPC is toting around the in-game proof!)

---
RH is going to infiltrate DL's Clone's planet!

(Don't worry, though... RH isn't a good guy or a bad guy... He's just a dickhead.)

---
Did I mention Pixie can clone objects now? (Or when he has the cloning app in his Android, he'll be able to...)

One thing RH may be doing is cloning DL's clones. Each of them loses a little 'quality' each time they are copied.

Then, DL's clones start cloning RH!!!

Pixie must utilize the ```destroy``` command to end the madness! (This won't wipe out DL's original clone, of course...)


---


Just brainstorming...

**Comment by KVonGit** [comment]
...I also have a random glitch clone turn script...

At any moment, a glitch may appear (usually making the background color and text color one in the same).

Pixie will have to use JavaScript to fix it.

**Comment by KVonGit** [comment]
Hey, DL,

You know what?

If you don't control XanMag and me, this game will be CRAZY long!!!

(I've already figured how to insert a game within a game using \<iframe>... and I haven't even made a mini-game yet! (The mini game will provide a password Pixie will need in the main game.))


---

Fucking shit... You guys know what?

When can make this an ongoing thing...

A computer in the hub already accesses textadventures.co.uk, and I've tested it out and the games play right in the iframe thing (although, they probably time out...))

Anyway, even if the iframe thing doesn't work out, we could just have a way for Pixie to boot up the available games list. From there, we can just upload our mini-games/worlds and update the small details in the hub game.

Eventually, the hub game's Quests will be completed, and the endgame will be linked to ...

...but I want to release it A.S.A.F.P. at the same time! Pixie is going to love this shit, y'all!

**Comment by KVonGit** [comment]
DL,

I was in the zone when you first posted that, but I just re-read/actually read it and that is really good! Every bit of it! (Except Pixie has to give it to R.H.. He runs off with it, but he doesn't actually _steal_ it... (Semantics, I know, but...))

>That's no moon!

Ha-ha!

That's DEFINITELY going in!

---
So we have:

|Name|Good/Bad|Description|
|---|---|---|
|The Pixie|Our Hero|Hacks his way through the web of Quests he finds himself tangled up in!|
|HegemonKhan|Protaganist|The real HK.|
|HK|Appears to be antagonist|HK's clone?|
|Richard Headkid|Appears to be an antagonist|RH is the alternate personality of KV. (Not a clone, but a pseudonymythic entity)|
|K.V.|Protagonist|K.V. is just this guy; you know?|
|DL|Protagonist|DL is not the clone of DL. He is the real DL. (Right?)|
|DL|Appears to be an antogonist|DL is the clone of DL.  Or is he?!?|
|XanMag|Protagonist|XanMag's just chilling/freaking out. (Examine him. Notice things. Ask him stuff.)|

---
# Maybe...

The clones are each out to get a shard. (R.H. just has a case of the fuck-arounds. He's a dickhead.)

Pixie can't stop all of them, plus he has other Quests to complete...

The clones and RH really aren't bad guys. They're just spreading out the shards to set up the group project! (We don't find that out until the third act of the group project, though.)

---
I can take my elaborate bits out and make a stand-alone game/side-quel. (I really, really want to see/hear/read Pixie's reaction to a lot of the stuff that we've got already, as well as the stuff I've been coming up with in the past 24 hours!)



I'm okay with my part of a prequel/tribute to Pixie being a short chase through 3 or 4 rooms, BUT I haven't put that much into the story, and XanMag definitely has.

Also, after playing through what we have already written, I don't really see the story sticking to ANY overall plot (besides the author constantly fucking with Pixie)...



It was more akin to a three level thing (maybe four), each of us taking Pixie through our own world, one at a time.

That was just the feeling I got from it, anyway...

...but I don't know... I made sure to use something from DL's world to really kick my part of the story off...

Hrmm... 

I like what we've got already AND the new idea...

I'm pretty sure XM has most of his rooms and puzzles envisioned already, too...

---
My instinct says to make my part just a LITTLE BIT longer, then pass the yarn off to XM.

Once he's done making Pixie run around like a crazy person, it can go right into the plot you (DL) just described then this game can end on a cliffhanger, if we want it to...

NOTE: I'll add little stuff for my NPCs to do once you guys write the new scenes.

---
After playing everyone's first submissions, I'm VERY excited to see what comes next out of both of you!!!

**Comment by KVonGit** [comment]
Hub
So, this is the hub... 

There are several people wandering around here, working on different things sometimes together, sometimes alone.



You can see XanMag, Richard Headkid, HK, a brochure, posts, a group project and post 23346.
You can go to DL's Room.

\> clone DarkLizerd
You can't clone DL. (He is copy-protected.)

\> clone XanMag
Done.

\> l
Hub
So, this is the hub... 

There are several people wandering around here, working on different things sometimes together, sometimes alone.



You can see XanMag, Richard Headkid, HK, a brochure, posts, a group project, post 23346 and XanMag.
You can go to DL's Room.

**Comment by KVonGit** [comment]
``` C++
foreach (o, AllObjects()) {
  if (o = GetObject(text)) {
    if (StartsWith(o.name, "Dark")) {
      msg ("You can't clone DL. (He has recently copy-protected himself.)")
    }
    else if (HasAttribute(o, "nocopy")) {
      msg ("You can't clone " + o.gender + " due to copy-protection.")
    }
    else {
      CloneObjectAndMove (o, player.parent)
      msg ("Done.")
    }
  }
}
```

**Comment by DarkLizerd** [comment]
> clone DarkLizerd
You can't clone DL. (He has recently copy-protected himself.)
I like it, but go one better...
> clone DarkLizerd
Are you sure you want to do that? Don't you think there are enough of him already?
> clone DarkLizerd
OK, fine! Be that way! Another clone of DarkLizerd strings into existence and run off to join the rest to translate Basic to Quest... (hopefully, unless they start fighting again about who is the original and who is the clone.)

**Comment by KVonGit** [comment]
>\> clone DarkLizerd
Are you sure you want to do that? Don't you think there are enough of him already?
\> clone DarkLizerd
OK, fine! Be that way! Another clone of DarkLizerd strings into existence and run off to join the rest to translate Basic to Quest... (hopefully, unless they start fighting again about who is the original and who is the clone.)

Ha! I was trying to reign myself in... I got WAY out of hand with all the Quest programming features I just added in!!!

---
There's also a bit where Pixie can USE THE TANDY. (He writes a program that runs flawlessly, using the BASIC programming skills he's acquired from DL.)

---
XanMag is most likely worn out because school just started back. (Somebody give that guy some beer! A LOT OF BEER!!!)

**Comment by KVonGit** [comment]
# YOU are The Pixie!

You must acquire and use your super-programming powers to complete this Quester's Quest of all Quests!

---
DarkLizerd's clone has cloned himself (and so on and so forth), and he now is an army of one, with one mission:

Collect the **Shards of Infinity** and use them to power ***The Disk of Infinite Improbability***!!!


Will the dastardly double of DarkLizerd's diabolical designs deem DL dimensially dictatorial, or will The Pixie's programming powers prevail???

---
# SHARDS OF &infin;
## PART ZERO
### THE PIX'S LAMENT
#### by David Agnew

**Comment by KVonGit** [comment]
``` C++
if (StartsWith(o.name, "Dark")) {
  Ask ("Are you sure you want to do that?  (Don't you think there are enough of him already?)<br/><br/>Would you REALLY like to clone DL?") {
    msg ("@@@open@@@ OK, fine! Be that way! @@@close@@@<br/><br/>Another clone of DarkLizerd springs into existence and runs off to join the rest to translate Basic to Quest... (hopefully, unless they start fighting again about who is the original and who is the clone.)")
  }
}
else if (HasAttribute(o, "nocopy")) {
  msg ("You can't clone " + o.gender + " due to copy-protection.")
}
else {
  CloneObjectAndMove (o, player.parent)
  msg ("Done.")
}
```

**Comment by KVonGit** [comment]
# PIXIE'S QUEST

**Comment by KVonGit** [comment]
#### Okay, check this out, gentlemen...

A funny thing happened on my way ~~~to~~~ through the forum.

I was perusing code samples, and one of Pix's listed his file's local address, and the folder was called quest-master. (Enter DIR while playing our game and note the system and directory information up top.)

So, here's what I'm thinking:

Our main game series' name might be:

# QUEST MASTER

This game might be:

# QUEST MASTER
##     PART NULL
# THE PIXIE'S QUEST
### by The Quest Forum

----
Then, the group project:

# QUEST MASTER
##     PART ONE
# SHARDS OF &infin;
### by David Agnew

**Comment by KVonGit** [comment]
...or maybe this is 

# SHARDS OF &infin;
## PART ZERO
# THE QUEST MASTER
### by The Quest Forum

**Comment by KVonGit** [comment]
I vote for:

# Pixie's Quest

**Comment by XanMag** [comment]
Pixie's Quest is fine with me.
