### ISSUE TITLE
Real names in the credits

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#40]
I kind of hid our real names in the special thanks at the end of the credits, but they're not hidden very well at all, honestly.

Who cares and who doesn't?

---
@XanMag 
- [ ] Real name's okay
- [ ] No real name

@DarkLizerd 
- [ ] Real name's okay
- [x] No real name

---
I ask because I'm about to make it a video instead of an HTML, and Adobe Premiere usually utterly perturbs me somehow every time I use it...

**Comment by DarkLizerd** [comment]
I would have said no. I try to keep the "two ME's"  separate... but as long as no one can connect the real me to the online me... who cares???
(How did you find out by the way???)

**Comment by KVonGit** [comment]
>I would have said no. I try to keep the "two ME's" separate... but as long as no one can connect the real me to the online me... who cares???

I took it out.  It's no problem.  I just have the credits saved as an HTML file right now, anyway.

If you go out of the way to keep it separate, that's what I'll do, too.

**Comment by DarkLizerd** [comment]
No, go ahead an leave it in... If nothing else, someone is going to wonder who the stranger is... 
Without a direct connect between the two, it will be just yet another mystery...

**Comment by KVonGit** [comment]
This is what I've got right now:

http://media.textadventures.co.uk/games/cNFLuCu1cUqmUv0I9_KEIQ/index.html

**Comment by DarkLizerd** [comment]
add:
and featuring a child of Bastet
(let everyone figure that one out!!!)
Bastet was an Egyptian goddess.
https://www.bing.com/search?q=Bastet&form=EDGSPH&mkt=en-us&httpsmsn=1&refig=12e8c321f03740a3ba1ebf71aa8a4bd6
I used that as a basis for my female "cat pet".

**Comment by KVonGit** [comment]
I thought Bast was a dead give away...

**Comment by KVonGit** [comment]
![image](https://user-images.githubusercontent.com/30656341/30793141-6e224420-a185-11e7-8937-a3e12dfdd799.png)

**Comment by KVonGit** [comment]
I moved her down by Alex Warren

![image](https://user-images.githubusercontent.com/30656341/30793231-0a25f790-a186-11e7-87eb-32c077bf3f43.png)

**Comment by DarkLizerd** [comment]
Wasn't sure...
Some references can be vague at best...
For my other game, I dreamed up their multi- million year history and what their worlds were like and their technology and major achievements... and their downfall... (kind of a sad story there)
This is a side effect of driving for a job and having a lot of free time to "play between my ears"...
That is why they call themselves Bast, or the children of Bastet...

**Comment by KVonGit** [comment]
If they're in the group project, you should totally add a page to the world wiki!

It can be a story, or short story, or something.  It doesn't have to look like a wiki page.

https://github.com/KVonGit/world-wiki/wiki

**Comment by DarkLizerd** [comment]
I have thought of writing it down. I just not sure what format would be best...
A history book?
A social history?
The life and times of the Bastet?
The fall of the Bastet?
The Bastet history of Earth?

**Comment by KVonGit** [comment]
See?

You can just do little snippets or long pieces or whatever in the world-wiki.

You can clone and download that wiki just like a repo.

Then, you'll have a wiki as a reference when you write your magnum opus!

**Comment by DarkLizerd** [comment]
Other than a manual for me to keep a backstory that matches when I re-use a Bast... Who would be interested in a fictional history even if some of the facts are taken out of mythology???
It may be an interesting read for someone if they wanted to know more about my "pet"...
If they knew there even was a back story...

**Comment by KVonGit** [comment]
>Other than a manual for me to keep a backstory that matches when I re-use a Bast... Who would be interested in a fictional history even if some of the facts are taken out of mythology???

Me.

...and probably Pixie.

...and definitely The Drunken Text Adventurer!  (And that's straight from the horse's ass's mouth!)

OUCH!!!

(The horse's ass just punched me in the arm.)

**Comment by XanMag** [comment]
https://youtu.be/2kE0bip9Ca8

**Comment by KVonGit** [comment]
Ha!

YouTube followed that up with Ace Ventura coming out of the rhino!

I remember watching that at the movies!  (Ace Ventura <s>2: Electric Boogaloo</s> :  When Nature Calls)

**Comment by KVonGit** [comment]
I removed our real names.

Closing this one out.

**Comment by DarkLizerd** [comment]
OK... Just HOW do I create a Wiki???

**Comment by KVonGit** [comment]
From the main repo's page, go to Wiki

![image](https://user-images.githubusercontent.com/30656341/30843747-d134fe24-a250-11e7-839f-33114a59f261.png)

And you should see a NEW PAGE button on the right (and the edit button):

![image](https://user-images.githubusercontent.com/30656341/30843752-e4731c3c-a250-11e7-8bd8-812de8eba26e.png)

Then:

![image](https://user-images.githubusercontent.com/30656341/30843776-08b13afc-a251-11e7-981c-84c84dc91f94.png)


![image](https://user-images.githubusercontent.com/30656341/30843780-12f7c1ca-a251-11e7-8080-27157b8027e3.png)

![image](https://user-images.githubusercontent.com/30656341/30843787-1b715d8e-a251-11e7-9386-9628f9f636d9.png)



---
If you can't edit or create a page, either one, let me know, please, sir.

**Comment by DarkLizerd** [comment]
I think I've set one up... but not the sidebar list like you have...
(yet)

**Comment by KVonGit** [comment]
I just restarted and Windows is updating...

It could be minutes, hours, or days...


Is it on my account's wiki?

You should be able to edit it.

**Comment by DarkLizerd** [comment]
I <B>think</B> I may have it...

**Comment by KVonGit** [comment]
Ha!

Probably, because I remember feeling the same way the first time I made a
wiki page.

They made the UI weird.

**Comment by DarkLizerd** [comment]
Yep...

**Comment by DarkLizerd** [comment]
Not planning to, I'm setting it up on my account, but there are 2 entries on your wiki...
Just tests...
If I could make sub-pages under the Bast page, then I would co that route...

**Comment by KVonGit** [comment]
You can link your pages together...

...or you can make yourself a second wiki (I think).

---
Have you played with Gists yet?

https://gist.github.com/

**Comment by DarkLizerd** [comment]
I think... looking at how your world-wiki is set-up, I think I know one way of setting mine up... (I think...)
I think I can set it all up as paragraphs under the Bast or Bastet page, then move them to separate pages as they evolve... 
As for playing with Gists... not before now...
If I set this up under my own account, how could I link it to yours so everyone can see it in one place without needing to chase it down on my page???

**Comment by DarkLizerd** [comment]
https://github.com/DarkLizerd/Random/wiki

**Comment by KVonGit** [comment]
>If I set this up under my own account, how could I link it to yours so everyone can see it in one place without needing to chase it down on my page???

I **think** I can add your page in my list of pages.

**Comment by DarkLizerd** [comment]
The Bast page has the link to my Wiki fro the Bast...
I think that will do.

**Comment by KVonGit** [comment]
>The Bast page has the link to my Wiki fro the Bast...
I think that will do.

Yep.

I can do it, but the side menu entries have to be entered individually.  There's a drop-down to click to show the regular menu after you add a custom one.

BUT the custom would look good and directly open you page...

...but then when someone clicked Home, it would take them to your home page.

---
We'll figure it out by the time we need it for the group project.

That's the REAL wiki anyway... or it will be.

I just set it all up because Pixie asked for one.  I have no idea what to fill it in with.

You should have access to do anything on there too, if you get bored:

https://github.com/KVonGit/world-wiki/wiki

**Comment by KVonGit** [comment]
I can just clone your wiki and drop the pages we want into my wiki.

That would be the easiest and least confusing way.

...not for this game, really, but for the group project.

Or we can shift the wiki link to your repo's wiki... That would work for me.

The wiki will be like our super-bonus game-guide wiki for the group project, with extras: stories, music, video?, pictures?, whatever...

Not only for the player, but for us to get a better handle on what each other have going on, too.

**Comment by DarkLizerd** [comment]
I got a basic started if you want to see...

**Comment by KVonGit** [comment]
Yes, please.

---
Also, how do you make your avatar?  I assume GitHub didn't just give you a DarkLizerdy color...

**Comment by DarkLizerd** [comment]
Follow the link in the Bast page...
I have a default avatar...

**Comment by KVonGit** [comment]
Ha-ha!  Nice avatar!

And the wiki page is good, too!

I'm pretty sure that's exactly the kind of stuff Pixie is wanting in that world wiki I made for the group project.

I don't think XM's map is current, but it's easy to replace all that stuff.

**Comment by DarkLizerd** [comment]
I don't think much from the original idea will stay the same...
