### ISSUE TITLE
Things missing messages

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#41]
There are many things with missing messages.

I added one of every default verb for 3 or 4 of my objects, and it made me tired.

I do know a pun master, though...

You guys think we should save him for the group project and just let the stuff in this one slide?

(He is NecroDeath, of The Bony King of Nowhere fame, by the way.)

**Comment by KVonGit** [comment]
I added these so far:

```xml
    <object name="Wumpus Cavern">
      <inherit name="editor_room" />
      <description><![CDATA[<br/>You enter the lair of the most feared Wumpus. Unlike most of the other caverns and tunnels, this one is massive!!!<br/>The cavernous roof towers over 40 feet above you! The far wall is over 100 feet away! There is a very large tunnel that leads off to the More. That must be how the creature makes it's way here. Looking about the cavern itself, you do not find the Wumpus, but the floor is uneven, but even at that, it could not hide from you. You make your way down towards the center of the cavern to the large brown grass covered hill. You carefully make your way around the hill keeping an eye out for where the creature could be. Without warning, the hill moves! It starts to get bigger!<br/>]]></description>
      <usedefaultprefix type="boolean">false</usedefaultprefix>
      <alias>Cavern Entrance</alias>
      <exitslistprefix>You can take the portal to </exitslistprefix>
      <firstenter type="script">
        kv_noScore.parent = game.pov.parent
      </firstenter>
      <exit alias="More" to="Wumpus Cavern2" />
      <command>
        <pattern>more;m</pattern>
        <script>
          HandleSingleCommand ("go more")
        </script>
      </command>
      <object name="roof">
        <inherit name="editor_object" />
        <look>It's at least 40 feet above you.</look>
        <scenery />
      </object>
      <object name="wall">
        <inherit name="editor_object" />
        <scenery />
        <look>It's at least 100 feet away.</look>
      </object>
      <object name="tunnel">
        <inherit name="editor_object" />
        <scenery />
        <look>It leads to the More.</look>
      </object>
      <object name="floor">
        <inherit name="editor_object" />
        <scenery />
        <look>It's uneven.</look>
      </object>
      <object name="hill">
        <inherit name="editor_object" />
        <scenery />
        <look>It's huge!  And it's moving!!!</look>
      </object>
      <object name="grass">
        <inherit name="editor_object" />
        <scenery />
        <look>It's coarse and brown.</look>
      </object>
    </object>
   
```

---
I'm not picking on you, DL.  Your part just comes first.

**Comment by KVonGit** [comment]
room5

```xml
      <object name="skeletons">
        <inherit name="editor_object" />
        <inherit name="plural" />
        <alias>skulls and bones</alias>
        <look>You'd rather not look at them too closely.</look>
        <scenery />
      </object>
```

**Comment by DarkLizerd** [comment]
<exitslistprefix>You can take the portal to </exitslistprefix>
 I think this should just be a "more" statement. something to break up the reading so the player does not know what happens next.

<object name="tunnel">
        <inherit name="editor_object" />
        <scenery />
        <look>It leads to the More.</look>
      </object>
If you are referring to the larger tunnel...
It leads to the surface, it is the Wumpus's exit. it is too large to fit through the smaller passages that Pixie came through.
But the player does not have time to find this out for sure, and there is no light coming in from outside that way.

Otherwise, looks good.
Well, someone has to be first... And (hopefully) it would be the easiest...
I think it was the first section added...
Well, my world was, the dream part was the last part.

**Comment by KVonGit** [comment]
>You can take the portal to 
>>I think this should just be a "more" statement. something to break up the reading so the player does not know what happens next.

You did that, I didn't.  (I'm watching you now, DL.)

Or did XanMag do that?

---
I thought the same thing, though.  I preferred the first way.  No mention of a portal.


---

<samp>
You enter the lair of the most feared Wumpus. Unlike most of the other caverns and tunnels, this one is massive!!!

The cavernous roof towers over 40 feet above you! The far wall is over 100 feet away! There is a very large tunnel that leads off to the More. That must be how the creature makes it's way here. Looking about the cavern itself, you do not find the Wumpus, but the floor is uneven, but even at that, it could not hide from you. You make your way down towards the center of the cavern to the large brown grass covered hill. You carefully make your way around the hill keeping an eye out for where the creature could be. Without warning, the hill moves! It starts to get bigger!


You can take the portal to [More]().

</samp>

---
That's where the tunnel, floor, wall, hill, and grass came from.

I'm just filling in things that were mentioned.

People will try interacting with everything mentioned, either in an effort to figure out what to do in the room, or just to find something we didn't include.

**Comment by KVonGit** [comment]
One of my friends, we'll call him The Drunken Text-Adventurer (or David for short), came over and played the game for a bit.

He tried to interact with all that stuff as I watched him play, and I realized I would have tried to interact with most of it, too, if I were just the average player.

He's a MONSTER!

If there's a bug or a hole, that bastard goes straight to it!

(I may have to kick his ass when he makes it to my parts!)

**Comment by DarkLizerd** [comment]
Nope... I'm dodging that one...
Quest did it... I just didn't think to look at the default exit descriptions that Quest uses...
Altho I did change most of the others for the dream sequence...

So, The Drunken Text-Adventurer is our first live victim of this beast... 
(I pity him... and what we will need to do because of him...)

**Comment by KVonGit** [comment]
I won't go overboard like I do in my own games.

...if I mention it, you at least get a description, if not a funny response.

(I delete a lot of my prose, in an effort to keep from making 1,000 scenery objects!)

If you're outside, there's a sky (and probably a sun or moon and some clouds) and there's ground.

If you're inside, there's always at least one wall, ceiling, and roof.

If I mention a door, you can examine it.  (That's easier in Inform 7.  So are containers.)

---
No one has probably ever examined any of those things, but, if they do, it will be there.

---
The good thing that comes out of deleting prose that would cause me to add extra scenery:

It makes the text adventure go more smoothly.  Before I edit my first draft, the text ALWAYS fills the screen when you enter a room.

(I have MUCH too much time on my hands!)

**Comment by KVonGit** [comment]
>So, The Drunken Text-Adventurer is our first live victim of this beast...
(I pity him... and what we will need to do because of him...)

He LOVED your stuff!  Especially everything in your room and the Bast.  

He's the guy that writes the Ralph the Penguin stories I borrow that notable from for my games.

Every time he interacted with ANYTHING you wrote, he nearly pissed himself.  (I still laugh at most of it, myself.  It's GOOD!)

**Comment by KVonGit** [comment]
He'll give up when he gets to XanMag's parts.  He goes crazy when he's gotta backtrack over and over again.  (F--k him!  Right, XM?  Lazy bastage!)

Even if he makes it through XM's tasks, he'll never make it through Crate Mart without the hints.  You pretty much need to know Quest programming in there.

**Comment by DarkLizerd** [comment]
From what I read somewhere... game writers may add in as much as 50 to 100% more text to a game than what the average player will ever read... But, it is better that it is there than missing...
Nothing worse than...
You enter the room, there is a smoking cigarette in the ashtray and a still cold beer on the desk...
X desk
I don't see that.
X beer
I don't see that.
x ashtray
I don't see that.

Personally... I laughed at most of it too!!!
(And that was the point!!!)

**Comment by KVonGit** [comment]
...and ANYONE who tries to take that glitch might quit, if they didn't:

- pay attention to my first alert
- know how to use JS commands in Quest AND know read the bit that tells them they CAN use it
- clear the screen occasionally after trying to take it
- enter HINT after trying to take it
- use the Quest PX and read the fist alert I sent, then copy and paste the command to fix it

---
NOTE: DON'T F--K WITH THE GLITCH!

**Comment by KVonGit** [comment]
>Personally... I laughed at most of it too!!!
(And that was the point!!!)

Oh yeah... Most of it...

But you create tension and a feeling of adventure, too.

That's why I was pushing you to add stuff to the world wiki.

I bet your stories would get away from you once you got to writing them in separate little chunks.

**Comment by KVonGit** [comment]
>game writers may add in as much as 50 to 100% more text to a game than what the average player will ever read... But, it is better that it is there than missing...

You damn skippy!

...and I'm one of the assholes who DOES read all that text.  (When it's Adams or Meretzky, you're missing out if you don't examine everything at least twice, die in every possible fashion, and all sorts of other things that render the game unwinnable.)

---
Hell, I'm about to write a guide for my parts of the game, and I bet it's not a quick read itself!

**Comment by DarkLizerd** [comment]
I looked at the code...
I could tell it was a "hands off" thingy...
The playtesting I've done so far, was:
My area (easy)
chasing after KV after taking the disk
and XM's beat lab...
and that's it...
Up to about 0.0.26 I think...

As I have commented else where, maybe here, when I write, it is like I tune into another world and I just type what I see... I usually have no control over the story until I back up to see what I write.

**Comment by KVonGit** [comment]
Your parts all full of awesome details, tension, and a feeling that there's a grand back-story.

XM is all about conversation and running Pixie back and forth in this one.

I have RH lead him on a short romp into the absurd.

Then... once he's completed everyone's bits, he can get into Crate Mart, where he must use his super-programming powers to progress.

Then, he's back in your hands.

---
It's pretty damned sweet, if you ask me.

He has to start and end with you, but he can do mine or XanMag's in whatever order he wants.

---
>when I write, it is like I tune into another world and I just type what I see... I usually have no control over the story until I back up to see what I write.

Me too.

And it happened here more than it ever has before! I cut half the stuff I wrote out and pasted it into a file to save for something else in the future.

---
>I looked at the code...
I could tell it was a "hands off" thingy...

What'chu talkin' 'bout, Willis?

**Comment by KVonGit** [comment]
<samp>

He thinks a while and disappears behind a curtain. Odd, you didn't notice that curtain before...

</samp>

---
Toying with the notion of making a curtain object, which is scenery.

Upon examination:


<samp>
"You can't see that!" says XanMag.

</samp>

**Comment by XanMag** [comment]
Yes!  I was making a wizard of oz reference with that by the way.

**Comment by KVonGit** [comment]
I had written **_"Don't mind the curtain," says XM_**, but decided to avoid the double-whammy.

**Comment by XanMag** [comment]
Any 'depth' you want to add is fine with me!

**Comment by KVonGit** [comment]
I think we're deep enough.

Closing this issue out.
