### ISSUE TITLE
The Envelope and the Idea

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#42]
What if the envelope's takemsg is:

 "You can't take XM's envelope.  (You're not above adding something to it, though.)"

 ---
Also, it's **envelopeXM** until ```notepad pencil.tranlsatedXM = true```, then it switches to ***IdeaInAnEnvelopeXM*** when pixie puts the translated notepad into it.

At that point, Pix goes and asks XM about it.  (Perhaps that should be a case on TELL XM ABOUT as well...)

---
This seems like the way you picturing it, XM...

**Comment by XanMag** [comment]
BINGO!!  Greatest beta tester ever!

**Comment by KVonGit** [comment]
You're a beta tester...

**Comment by KVonGit** [comment]
You think Gal Gadot plays text adventures?

She'd be a fantastic beta tester, I bet...

**Comment by XanMag** [comment]
She could test my beta.  If you know what I mean...

**Comment by KVonGit** [comment]
Okay, XanMag,

The envelope can't be taken now, but you can put the idea in it, no matter what.

I just need the response that prints when the notepad is translated.

```C++
switch (object) {
  case (notepad pencil) {
    if (notepad pencil.translatedXM) {
      msg ("NEED A MESSAGE.")
      RemoveObject (notepad pencil)
      RemoveObject (envelopeXM)
      MoveObject (IdeaInAnEnvelopeXM, pedestalXM)
    }
    else {
      msg ("Done.")
      MoveObject (notepad pencil, envelopeXM)
    }
  }
  default {
    msg ("You can't put " + object.article + " in there.")
  }
}
```

**Comment by KVonGit** [comment]
<samp>

It puts the lotion on its skin or else it gets the hose again!

</samp>

---
OR

---
<samp>

You put the idea into the envelope.  (Now you should probably go talk to Xan about it, and see if the idea took root.)

</samp>

---
Or something...

**Comment by XanMag** [comment]
So... the envelope is not takeable and remains on the pedestal at all times?  The scramble gets unscrambled and written In the notepad?  You then must put the notepad in the envelope?

You put your edited version in the envelope in the hopes that it might help XM get over his writers block.

?

**Comment by KVonGit** [comment]
...and, being that the envelope is in XM's mind, the idea has been planted?


...then, asking XM about it rings the metaphorical bell?

**Comment by KVonGit** [comment]
I was just thinking that that's what you were thinking...

What you were you thinking?

**Comment by XanMag** [comment]
That.  Lol

**Comment by KVonGit** [comment]
Guess what, then?

C.

L.

O.

S.

E.

D.
