### ISSUE TITLE
HK

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/HVACR-specifications#5]
Are we gonna write him in? Or write him out?

HK' description (in my mind):

> HK/hegemonkhan/HegemonKhan is looking/staring/glowering at you, as if you were bothering/perturbing/disturbing him.

---
NOW...

That's not me 'poking fun at', that's me 'having fun with'.

I am bad/good about using/writing/utilizing forward slashes to explain/confound things myself.

If HK might not find that funny / might find that offensive, I'd rather exclude it.

---
NOTE: I plan to make very much fun of myself.

In fact, I encourage you to point out anything you find humorous about me/my online activities.

I'll put it in the game.

I.e.,

I think there should be a bit where HK and I are miscommunicating like a motherfucker, and Pixie has to TELL KV ABOUT ```LCase``` (or something to that effect).

Also, while I'm off-topic, I want more DL clone action!!! That shit is FUNNY!

**Comment by XanMag** [comment]
Oh boy.  That's some good stuff!!
Of course, this is taking longer than I thought.  Having trouble with the AND bit... 

    On Sunday, August 13, 2017 10:39 PM, K.V. <notifications@github.com> wrote:
 

 Are we gonna write him in? Or write him out?HK' description (in my mind):
HK/hegemonkhan/HegemonKhan is looking/staring/glowering at you, as if you were bothering/perturbing/disturbing him.
NOW...That's not me 'poking fun at', that's me 'having fun with'.I am bad/good about using/writing/utilizing forward slashes to explain/confound things myself.If HK might not find that funny / might find that offensive, I'd rather exclude it.NOTE: I plan to make very much fun of myself.In fact, I encourage you to point out anything you find humorous about me/my online activities.I'll put it in the game.I.e.,I think there should be a bit where HK and I are miscommunicating like a motherfucker, and Pixie has to TELL KV ABOUT LCase (or something to that effect).Also, while I'm off-topic, I want more DL clone action!!! That shit is FUNNY!—

**Comment by KVonGit** [comment]
The AND bit can SUCK IT!

I just make it a nested IF...

Quest changes it to that anyway...

**Comment by XanMag** [comment]
I can tell it is getting late when I make a STUPID FUCKING mistake like this one...
Goddamned if I didn't fiddle around with this AND shit for 45 minutes to realize the flag I was trying to check for in the If statement was set on something else.  Code incoming! 

    On Sunday, August 13, 2017 10:44 PM, K.V. <notifications@github.com> wrote:
 

 The AND bit can SUCK IT!I just make it a nested IF...Quest changes it to that anyway...—

**Comment by DarkLizerd** [comment]
I'm bad with names as such, and I don't have a list of the player here, so...
HK dropped out of the main project, yes? (and why?)
Could we invite him back in for this? If not to add code, then just to make suggestions on how to run his character?
I, personally, could be offended if I was used in a game and not warned before hand.

**Comment by KVonGit** [comment]
>HK dropped out of the main project, yes? (and why?)

Well, when I invited him to participate in the main project, he said he might submit some codes from time to time, and that he's offer up suggestions, but that he probably wouldn't submit actual story.

Then, he set up a GitHub account and submitted this: https://github.com/KVonGit/Quest-Group_Project/blob/master/programming_docs/dynamic_menu_function.xml.

He deleted his account shortly thereafter.

NOTE: He's also told me a few times that the forum is the only online account he's inclined to have. No Gmail, Yahoo!, or any of that. (This made me think his submission was a sure sign of his interest in the project. (Him setting up the GitHub account in the first place, I mean.) Then, all the issue notifications probably discouraged the hell out him, and he closed down his GitHub account. (This is just my wild theory.)

---
>Could we invite him back in for this? If not to add code, then just to make suggestions on how to run his character?

Definitely. I thought you or XM may know him better than I (and my plan was to ask one of you to ask him again), but I can totally ask him again.

>I, personally, could be offended if I was used in a game and not warned before hand.

Yeah... I keep wanting to say that I wouldn't be offended (the opposite, in fact), but I'm not so sure.

...and I don't want to risk offending HK. I like the shit out of that guy! (Not that I'd want to risk offending anyone, whether I liked them or not, mind you... I just meant 'especially HK'. You guys know what I'm saying, know what I'm saying?)

---
I'm message him right now.

More on this as it comes in...

**Comment by KVonGit** [comment]
UPDATE:

I sent HK a message through the textadventures message system earlier.

 (I think I did, at any rate... I was half asleep, and I have no outbox...)

**Comment by KVonGit** [comment]
I'm sure everyone saw the comment about HK leaving the project on the main project's issue, but...

He gave his permission for us to use him as an NPC, and seemed to like the ideas I listed in the above comments.

I'll add the stuff in later on today.

---
PS

I'm checking the game back in.

**Comment by KVonGit** [comment]
[#top](#top)
