### ISSUE TITLE
Overlapping/Relationships

### ISSUE THREAD

**Issue by XanMag** [KVonGit/HVACR-specifications#8]
I plan on having some, if not all, of the following as items/dialogue in my portion of the game somewhere:
- a Ralph poster (in my daydreaming room)
- occasional, and subtle references to They Call Me Mister
- I'd like to try to find quotes or snippets of posts of contributing authors on the forum - again subtle and not real important... kind of an easter egg type thing
- more to come AFTER I figure out what to do next in Bony King...

**Comment by KVonGit** [comment]
![rp](https://user-images.githubusercontent.com/30656341/29258423-1e9b2ed4-807f-11e7-9a9d-c0a4960758a6.png)

Ralph's author's rendering 


---
I ported Bony King to Glulx, so don't be hinting about needing hints around me...


---
I included your Land Rover (in a strange way) already.

I was sort of thinking about making Pixie play an alternative version of the riddle scene from Dragon's Den, but I'd need help to keep it true to the original...

---
@DarkLizerd 

We want a WUMPUS bit!!!

(Don't we?)

WUMPUS! WUMPUS! WUMPUS!

---
And what about The God Device?

Should it be referenced?

I haven't got around to playing Deeper or the Myothian Falcon...

**Comment by KVonGit** [comment]
/> open Tandy Color Computer 2
It appears to be stuck closed. (Maybe XanMag can get it open...)

Okay, XM...

If Pixie brings this to you and asks you to help open it, you'll just make fun of him, right?

**Comment by KVonGit** [comment]
You want to send Pixie on a beer Quest?

We could even clear the screen and throw up a fake title splash:

<center><h1>BEER QUEST</h1><center>
<h2> The Pixie's Run</h2>

It could be a timed driving adventure...

You could really need a fucking beer at some point, right? (You DO keep sipping on them, and they DO eventually disappear...)

---
Wait...

Maybe I should play your part through before I assume you haven't already included such a thing...

**Comment by KVonGit** [comment]
I want RH to show up in the hub with KV once what we all have so far has been completed.

@XanMag, I added on to your dance command. (I got cardboard, bitches!)

@DarkLizerd, would DL join in if everyone else were dancing? Would he walk the dinosaur? (Boom, boom. Shacka lacka lacka boom.)

RH and KV will argue about the way a script should be written...

Enter DL's clone??? (Or is the DL in the hub the one that's the clone? (When I changed the gender from 'it' to 'he', was that me fucking up what DL was using as a way to tell us the one in the hub is the clone?!?!?!?!?))

---
The answers to these questions, and many more, in the next episode of:

# INSERT GAME TITLE HERE

(I don't know if I'm digging **TRIBUTE** or not...)

---
PostScript:

I've been removing TAKE and USE from the appropriate verb lists.

**Comment by DarkLizerd** [comment]
One thought, after we let Pixie play this, we are going to release this to the general public, right???
If so, at the start, we need:
"Are you Pixie? (Yes or No)"
If No, then enter your name...
I ask, because when I played through what we got so far, it felt strange to be called Pixie...
The "if not Pixie" player needs a slightly different handling than if it IS Pixie...

**Comment by KVonGit** [comment]
>One thought, after we let Pixie play this, we are going to release this to the general public, right???

If you guys want to, we can.

I was aiming for a 'Pixie's eyes only' sort of thing, but it is turning out to be pretty damned good...

...but I think that's mainly because we're writing it for Pixie...

We've also got some Quest-related puzzles cooking up for him to solve. (One plan is to plant things in the Quest forum that he'll have to access while playing the game, and I very much like that idea!)

So, I think most of it will seem off-putting to ~~~the average player~~~ anyone besides Pixie anyway.

---
I'll probably change the dialogue on my NPCs if we plan to release it. It's a bit more detailed (not exactly more _personal_... just more detailed) than what I'd want if this will be available to everyone.

Again, I'm easily persuaded...

What'cha think, @XanMag?

Should we plan to share this with everyone?

Or should we make it just for Pixie?

---
Asking if the player is Pixie is a good idea, and it would work, but I'd vote to just make the Pixie's version, then edit appropriately to make a version for the public. 

It would be the same amount of writing, with less IF...THEN... statements, and no chance for anyone to see the stuff we included just for The Pix.

**Comment by XanMag** [comment]
I think we release it to everyone and not change a thing.  The player can assume the role of Pixie and I think that those who frequent the forums may get a kick out of it too? 

    On Tuesday, August 15, 2017 3:36 PM, K.V. <notifications@github.com> wrote:
 

 
One thought, after we let Pixie play this, we are going to release this to the general public, right???
If you guys want to, we can.I was aiming for a 'Pixie's eyes only' sort of thing, but it is turning out to be pretty damned good......but I think that's mainly because we're writing it for Pixie...We've also got some Quest-related puzzles cooking up for him to solve. (One plan is to plant things in the Quest forum that he'll have to access while playing the game, and I very much like that idea!)So, I think most of it will seem off-putting to  anyone besides Pixie anyway.I'll probably change the dialogue on my NPCs if we plan to release it. It's a bit more detailed (not exactly more personal... just more detailed) than what I'd want if this will be available to everyone.Again, I'm easily persuaded...What'cha think, @XanMag?Should we plan to share this with everyone?Or should we make it just for Pixie?Asking if the player is Pixie is a good idea, and it would work, but I'd vote to just make the Pixie's version, then edit appropriately to make a version for the public.It would be the same amount of writing, with less IF...THEN... statements, and no chance for anyone to see the stuff we included just for The Pix.—

**Comment by KVonGit** [comment]
>I think we release it to everyone and not change a thing.  The player can assume the role of Pixie and I think that those who frequent the forums may get a kick out of it too?


I can get with that.

(Like I say: easily persuaded!)

---
KV

- [ ] Ask 'are you Pixie?'
- [ ] Fuck it. It's the Pixie game. You're Pixie.

XM

- [ ] Ask 'are you Pixie?'
- [ ] Fuck it. It's the Pixie game. You're Pixie.

DL

- [ ] Ask 'are you Pixie?'
- [ ] Fuck it. It's the Pixie game. You're Pixie.

**Comment by KVonGit** [comment]
Maybe the title should be:

# For Pix

or 

# @ThePix

or maybe just 
# TRIBUTE


---
I'm not really feeling any of those, though...

**Comment by XanMag** [comment]
This Week's Pix...  

    On Tuesday, August 15, 2017 4:01 PM, K.V. <notifications@github.com> wrote:
 

 Maybe the title should be:
For Pix
or
@ThePix
or maybe just
TRIBUTE
I'm not really feeling any of those, though...—

**Comment by KVonGit** [comment]
>This Week's Pix... 

Ha-ha!

or 
# The Pixie's Quest (version 5.7.69105)

**Comment by DarkLizerd** [comment]
If nothing else, then just changing "Hi Pixie" to "Hi " + player.alias for the most part is all that would be required...
And for Pixie explicit stuff... If player.alias="Pixie" then (do this)
Then the player has the choice of seeing why the name Pixie was so important...

**Comment by KVonGit** [comment]
We could make a command?

Command pattern:
```I AM #text#```

```
if (not player.alias = text) {
player.alias = text
msg ("Hello, " + text + "! I'm your parser! It's a pleasure to meet you!
")
}
else {
text1 = ListItem(Split(text, " "), 0)
 msg ("I know, " + text1 + ", I know... You've already said that. (Have you been drinking XanMag's beer?)")
}
```
---
>\> i am motherfucker jones
Hello, motherfucker jones! I'm your parser! It's a pleasure to meet you!
>
>\> g
(i am motherfucker jones)
I know, motherfucker, I know... You've already said that. (Have you been drinking XanMag's beer?)
>
>\> msg (player.alias)
motherfucker jones
>
>\> i am KV
Hello, KV! I'm your parser! It's a pleasure to meet you!
>
>\> g
(i am KV)
I know, KV, I know... You've already said that. (Have you been drinking XanMag's beer?)
>
>\> msg (player.alias)
KV


---
And, yes: you can use ```msg (player.alias)``` or ```msg ("Hello world!")``` or ```msg (XanMag.aware)``` during play, and it works just like it would in a script.

**Comment by KVonGit** [comment]
You know how the dedicate books in the beginning?

Like in Stephen King's **The Shining**:

>"This is for Joe Hill King, who shines on."


---
Well, how about:

Instead of the current first line in the opening splash screen:

>This game is for The Pixie. Thanks for everything you do!

...we put...

>For Andy, who aids in every Quest.


Or something cooler...

...but should we say "Andy" or stick with web handles?

**Comment by DarkLizerd** [comment]
From where this is heading... I'm not so sure that the average, or sub-average, Quest player can follow this tribute. For this to be played by just anyone, it will need to be scaled WAY back...

**Comment by KVonGit** [comment]
Yeah...

I kept posting that the game had taken on a life of its own...

I tried to put a leash on that bitch, but to no avail...

Quest is like, "Pixie would LOVE this!" Then, it just moves my fingers to the correct keys. I've been on autopilot for four days!

---
I am toning it back down now, though.

I started on that last night.

---
My offer still stands, too:

I can take all my stuff out and make a stand alone game for Pixie with all my Quest commands and such.

I'd just leave the little bit in that I had at first, and add a very small hide and seek puzzle.

I thought we'd voted to say 'the hell with everyone else; if they can hang, so be it' and just make it for Pixie, though... 

I'm sorry about all that!

**Comment by DarkLizerd** [comment]
I say leave it in, but there needs to be a good hint system for the "non-Pixie" players to figure it out.
(I wonder if Quest could have access to the PC log-in info, and get the player from that?)
Then the Non-Pixie player would have auto access to the help, and Pixie is left out in the cold to figure it out.
(Here is where the player name would help!)

**Comment by KVonGit** [comment]
You can enter REAL HELP or ACTUAL HELP for the good stuff.

Plus, I've added Pixie's magic book of spells to the player's inventory since version 22.

---
I'm also adding a hintTopic attribute to each object I'm making for whoever accesses it.

---
I put the player name command in there for you, as well. I don't remember which revision that was, though.

**Comment by KVonGit** [comment]
The Quest PX device accesses the available commands, the Quest docs, the Quest forum, the messages we include in the alerts thingy, and more.

Plus you can enter: cat 4px.aslx and view the actual source code. (I'm putting an IF...THEN... on this, just like I made copy-protection when I added the cloning commands.)

**Comment by KVonGit** [comment]
@DarkLizerd 

You should also USE THE TANDY on KV's desk!!!

**Comment by KVonGit** [comment]
# The Ending

So, I've got these crates in Crate Mart, right?

What if each of us is in a different crate, like 3-card monte, and we each are working on our computer in our respective crate?

The DL clones are pouring in in groups, searching for the shard that's in the mini-crate, and Pixie has to fight them off (using the DESTROY (#OBJECT#) 'spell' in his magic book) while using the CHEAT SET LARGE CRATE.ISOPEN = TRUE spell to get into the crates, get to each of us, and stop us from writing any more of this damned game!

Upon puzzle completion, some vaguely described something swoops in, grabs the shard from DL, and leaves us hanging on the cliff that faces the real group project.


---
Maybe it's revealed (or hinted at) that Quest Towers is what's holding all of existence together...

The green shard powered the hub, and now it's gone!

# TO BE CONTINUED

**Comment by KVonGit** [comment]
...maybe the vaguely described something is the Wumpus? 

...or we THOUGHT it was just the Wumpus, but it's darker.... more evil...  


That would tie in the dream from the opening, too...

**Comment by XanMag** [comment]
Love it.
